<?php

namespace Database\Seeders;

use App\Models\JobPost;
use Illuminate\Database\Seeder;

class JobPostSeeder extends Seeder
{
    /**
     * Seed a realistic set of open roles for the public career page.
     * Idempotent: existing jobs with the same slug are updated, not duplicated.
     */
    public function run(): void
    {
        $jobs = [
            [
                'title' => 'Senior Backend Engineer',
                'slug' => 'senior-backend-engineer',
                'type' => 'full-time',
                'department' => 'Engineering',
                'location' => 'Kolkata, India',
                'is_remote' => true,
                'salary' => '18,00,000',
                'experience_required' => '5-8 Years',
                'skills' => ['PHP', 'Laravel', 'MySQL', 'Redis', 'AWS'],
                'vacancies' => 2,
                'featured' => true,
                'application_deadline' => now()->addDays(21),
                'published_at' => now()->subDays(3),
                'description' => 'We are looking for a senior backend engineer to own our donation processing pipeline. You will design reliable, auditable payment flows, scale our campaign APIs, and mentor a small team of engineers. If you care about building systems that process millions in donations without breaking trust, this is the role for you.',
            ],
            [
                'title' => 'Frontend Engineer (React)',
                'slug' => 'frontend-engineer-react',
                'type' => 'full-time',
                'department' => 'Engineering',
                'location' => 'Remote, India',
                'is_remote' => true,
                'salary' => '12,00,000',
                'experience_required' => '3-5 Years',
                'skills' => ['React', 'TypeScript', 'Vite', 'Tailwind CSS'],
                'vacancies' => 1,
                'featured' => false,
                'application_deadline' => now()->addDays(9),
                'published_at' => now()->subDays(6),
                'description' => 'Help us build a delightful donor experience. You will craft campaign pages, donation flows, and impact dashboards that make giving feel effortless. Strong fundamentals in accessibility and performance are non-negotiable; a love for polish is a bonus.',
            ],
            [
                'title' => 'Product Designer',
                'slug' => 'product-designer',
                'type' => 'full-time',
                'department' => 'Design',
                'location' => 'Bengaluru, India',
                'is_remote' => false,
                'salary' => '14,00,000',
                'experience_required' => '4-6 Years',
                'skills' => ['Figma', 'Design Systems', 'Prototyping', 'UX Research'],
                'vacancies' => 1,
                'featured' => true,
                'application_deadline' => now()->addDays(15),
                'published_at' => now()->subDays(2),
                'description' => 'We are shaping a brand that feels as warm as the causes it supports. You will own the end-to-end design of donor and NGO-facing products — from research and wireframes to polished, accessible interfaces and our design system.',
            ],
            [
                'title' => 'Growth Marketing Manager',
                'slug' => 'growth-marketing-manager',
                'type' => 'full-time',
                'department' => 'Marketing',
                'location' => 'Mumbai, India',
                'is_remote' => false,
                'salary' => '10,00,000',
                'experience_required' => '4-6 Years',
                'skills' => ['SEO', 'Performance Marketing', 'Content Strategy', 'Analytics'],
                'vacancies' => 1,
                'featured' => false,
                'application_deadline' => now()->addDays(30),
                'published_at' => now()->subDays(8),
                'description' => 'Own the growth loop from first visit to repeat donation. You will run campaigns across search, social, and email, partner with NGOs on co-marketing, and report on what actually moves the needle for our fundraisers.',
            ],
            [
                'title' => 'Content Writer',
                'slug' => 'content-writer',
                'type' => 'part-time',
                'department' => 'Marketing',
                'location' => 'Remote, India',
                'is_remote' => true,
                'salary' => '4,50,000',
                'experience_required' => '2-4 Years',
                'skills' => ['Storytelling', 'SEO', 'Editing'],
                'vacancies' => 2,
                'featured' => false,
                'application_deadline' => null,
                'published_at' => now()->subDays(5),
                'description' => 'Tell the stories behind the campaigns. You will write campaign features, NGO spotlights, and our fortnightly newsletter — work that helps donors connect emotionally and gives NGOs the visibility they deserve.',
            ],
            [
                'title' => 'Data Analyst',
                'slug' => 'data-analyst',
                'type' => 'contract',
                'department' => 'Operations',
                'location' => 'Remote, India',
                'is_remote' => true,
                'salary' => '9,00,000',
                'experience_required' => '3-5 Years',
                'skills' => ['SQL', 'Python', 'Power BI', 'Excel'],
                'vacancies' => 1,
                'featured' => false,
                'application_deadline' => now()->addDays(18),
                'published_at' => now()->subDays(11),
                'description' => 'Turn donation data into decisions. You will build the reporting layer our operations team lives on — fraud signals, campaign performance, payout accuracy — and present findings to leadership with clarity.',
            ],
            [
                'title' => 'NGO Partnerships Lead',
                'slug' => 'ngo-partnerships-lead',
                'type' => 'full-time',
                'department' => 'Operations',
                'location' => 'New Delhi, India',
                'is_remote' => false,
                'salary' => '12,00,000',
                'experience_required' => '5-7 Years',
                'skills' => ['Partnerships', 'Negotiation', 'Stakeholder Management'],
                'vacancies' => 1,
                'featured' => true,
                'application_deadline' => now()->addDays(6),
                'published_at' => now()->subDays(1),
                'description' => 'Be the bridge between DonateBazaar and the NGOs we serve. You will onboard mission-driven organisations, help them run successful campaigns, and advocate for the tools and support they need to scale their impact.',
            ],
            [
                'title' => 'Customer Support Associate',
                'slug' => 'customer-support-associate',
                'type' => 'full-time',
                'department' => 'Support',
                'location' => 'Chennai, India',
                'is_remote' => false,
                'salary' => '3,60,000',
                'experience_required' => '0-2 Years',
                'skills' => ['Communication', 'Empathy', 'CRM Tools'],
                'vacancies' => 3,
                'featured' => false,
                'application_deadline' => now()->addDays(45),
                'published_at' => now()->subDays(4),
                'description' => 'Be the first human our donors and fundraisers reach. You will answer questions about campaigns, refunds, and payouts with warmth and speed, and feed what you learn back to product and engineering.',
            ],
            [
                'title' => 'UI/UX Intern',
                'slug' => 'ui-ux-intern',
                'type' => 'internship',
                'department' => 'Design',
                'location' => 'Remote, India',
                'is_remote' => true,
                'salary' => '1,80,000',
                'experience_required' => '0-1 Years',
                'skills' => ['Figma', 'Wireframing', 'Design Fundamentals'],
                'vacancies' => 2,
                'featured' => false,
                'application_deadline' => now()->addDays(60),
                'published_at' => now()->subDays(9),
                'description' => 'A 6-month paid internship where you will work alongside our senior designers on real donor-facing features. You will leave with shipped work, mentorship, and a strong portfolio. Students and fresh graduates are welcome.',
            ],
            [
                'title' => 'Freelance Illustrator',
                'slug' => 'freelance-illustrator',
                'type' => 'freelance',
                'department' => 'Design',
                'location' => 'Remote, India',
                'is_remote' => true,
                'salary' => '60,000',
                'experience_required' => '2-4 Years',
                'skills' => ['Illustration', 'Branding', 'Procreate', 'Adobe Illustrator'],
                'vacancies' => 1,
                'featured' => false,
                'application_deadline' => now()->addDays(25),
                'published_at' => now()->subDays(7),
                'description' => 'Project-based illustration work for campaigns, social assets, and our annual impact report. A warm, human, editorial style is a must; experience with non-profit work is a strong plus.',
            ],
            [
                'title' => 'Volunteer Coordinator',
                'slug' => 'volunteer-coordinator',
                'type' => 'volunteer',
                'department' => 'Community',
                'location' => 'Remote, India',
                'is_remote' => true,
                'salary' => null,
                'experience_required' => '1-2 Years',
                'skills' => ['Community Building', 'Event Planning', 'Communication'],
                'vacancies' => 1,
                'featured' => false,
                'application_deadline' => null,
                'published_at' => now()->subDays(12),
                'description' => 'Run our volunteer community — onboarding new volunteers, organising skill-based donation drives, and keeping our channels buzzing. Unpaid but deeply rewarding; you will see your work change lives.',
            ],
        ];

        foreach ($jobs as $job) {
            JobPost::updateOrCreate(
                ['slug' => $job['slug']],
                array_merge($job, ['status' => 'active'])
            );
        }
    }
}