import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    server: {
        host: '127.0.0.1',
    },
    plugins: [
        laravel({
            input: [
                'resources/css/public/app.css',
                'resources/css/public/footer.css',
                'resources/css/public/chatbot.css',
                'resources/css/public/navbar.css',
                'resources/css/public/about.css',
                'resources/css/public/partnership.css',
                'resources/css/public/events-view.css',
                'resources/css/public/faq.css',
                'resources/css/public/ddrf.css',
                'resources/css/public/events-register.css',
                'resources/css/public/how-it-works.css',
                'resources/css/public/events-index.css',
                'resources/css/public/contact.css',
                'resources/css/public/auth.css',
                'resources/css/public/errors.css',
                'resources/css/public/errors-3.css',
                'resources/css/public/errors-4.css',
                'resources/css/public/job-posts-show.css',
                'resources/css/public/job-posts-index.css',
                'resources/css/public/public-show.css',
                'resources/css/public/events-public-show.css',
                'resources/css/public/home.css',
                'resources/css/public/volunteer-apply.css',
                'resources/css/public/blog-show.css',
                'resources/css/public/blogs.css',
                'resources/css/public/impact.css',
                'resources/css/public/legal.css',
                'resources/css/public/newsletter-unsubscribed.css',
                'resources/css/public/search.css',
                'resources/css/public/payment.css',
                'resources/css/public/campaigns.css',
                'resources/css/public/campaigns-create.css',
                'resources/css/public/campaigns-index.css',
                'resources/css/public/campaigns-old.css',
                'resources/css/public/campaigns-show.css',
                'resources/css/public/campaigns-show-new.css',
                'resources/css/admin/entries/core.css',
                'resources/css/admin/entries/dashboard.css',
                'resources/css/admin/entries/campaigns.css',
                'resources/css/admin/entries/categories.css',
                'resources/css/admin/entries/organizations.css',
                'resources/css/admin/entries/finance.css',
                'resources/css/admin/entries/events.css',
                'resources/css/admin/entries/jobs.css',
                'resources/css/admin/entries/blogs.css',
                'resources/css/admin/entries/applications.css',
                'resources/css/admin/entries/messages.css',
                'resources/css/admin/entries/misc.css',
                'resources/css/admin/entries/products.css',
                'resources/css/user/user.css',
                'resources/js/public/app.js',
                'resources/js/public/auth.js',
                'resources/js/public/home.js',
                'resources/js/public/contact.js',
                'resources/js/public/campaigns.js',
                'resources/js/public/campaigns-show.js',
                'resources/js/public/footer.js',
                'resources/js/public/chatbot.js',
                'resources/js/public/navbar.js',
                'resources/js/public/about.js',
                'resources/js/public/volunteer-city.js',
                'resources/js/admin/admin.js',
                'resources/js/user/user.js',
            ],
            refresh: true,
        }),
    ],
});
