<?php

return [
    'states' => [
        'Andhra Pradesh',
        'Arunachal Pradesh',
        'Assam',
        'Bihar',
        'Chhattisgarh',
        'Goa',
        'Gujarat',
        'Haryana',
        'Himachal Pradesh',
        'Jharkhand',
        'Karnataka',
        'Kerala',
        'Madhya Pradesh',
        'Maharashtra',
        'Manipur',
        'Meghalaya',
        'Mizoram',
        'Nagaland',
        'Odisha',
        'Punjab',
        'Rajasthan',
        'Sikkim',
        'Tamil Nadu',
        'Telangana',
        'Tripura',
        'Uttar Pradesh',
        'Uttarakhand',
        'West Bengal',
        'Andaman and Nicobar Islands',
        'Chandigarh',
        'Dadra and Nagar Haveli and Daman and Diu',
        'Delhi',
        'Jammu and Kashmir',
        'Ladakh',
        'Lakshadweep',
        'Puducherry',
    ],

    'cities' => [
        'Andhra Pradesh' => [
            'Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore', 'Kurnool', 'Rajahmundry', 'Tirupati',
            'Kakinada', 'Anantapur', 'Eluru', 'Ongole', 'Kadapa', 'Chittoor', 'Machilipatnam',
            'Tenali', 'Proddatur', 'Hindupur', 'Bhimavaram', 'Madanapalle', 'Guntakal',
            'Dharmavaram', 'Gudivada', 'Narasaraopet', 'Tadpatri', 'Amalapuram', 'Tadepalligudem',
            'Chilakaluripet', 'Kavali', 'Palasa', 'Srikakulam', 'Parvathipuram', 'Bobbili',
            'Salur', 'Vizianagaram', 'Narsipatnam', 'Yemmiganur', 'Adoni', 'Mangalagiri',
            'Piduguralla', 'Vinukonda', 'Sattenapalle', 'Narsaraopet', 'Repalle', 'Bapatla',
            'Ponnur', 'Narasapuram', 'Palakollu', 'Nidadavolu', 'Kovvur', 'Tanuku',
            'Kothapeta', 'Ramachandrapuram', 'Mandapeta', 'Pithapuram', 'Samalkot', 'Tuni',
            'Anakapalle', 'Vudadavalli', 'Atmakur', 'Kandukur', 'Kanigiri', 'Markapur',
            'Giddalur', 'Badvel', 'Pulivendula', 'Jammalamadugu', 'Rayachoti', 'Punganur',
            'Srikalahasti', 'Nagari', 'Puttur', 'Venkatagiri', 'Naidupet', 'Gudur',
            'Sullurpeta', 'Ichapuram', 'Kavali', 'Macherla', 'Gurazala', 'Darsi',
        ],
        'Arunachal Pradesh' => [
            'Itanagar', 'Naharlagun', 'Pasighat', 'Tawang', 'Ziro', 'Bomdila', 'Roing',
            'Tezu', 'Namsai', 'Changlang', 'Khonsa', 'Longding', 'Daporijo', 'Aalo',
            'Basar', 'Yingkiong', 'Anjaw', 'Koloriang', 'Palin', 'Nyapin', 'Raga',
            'Yupia', 'Doimukh', 'Sagalee', 'Seppa', 'Balemu', 'Jairampur', 'Miao',
            'Vijaynagar', 'Hayuliang', 'Mechuka', 'Monigong', 'Tuting', 'Gelling',
            'Dibang Valley', 'Anini', 'Etalin', 'Hunli', 'Koronu', 'Tali', 'Leparada',
        ],
        'Assam' => [
            'Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Nagaon', 'Tinsukia', 'Tezpur',
            'Bongaigaon', 'Goalpara', 'Barpeta', 'Diphu', 'North Lakhimpur', 'Sivasagar',
            'Hailakandi', 'Karimganj', 'Dhekiajuli', 'Rangia', 'Raha', 'Mangaldoi',
            'Udalguri', 'Bilasipara', 'Dhubri', 'Gauripur', 'Kokrajhar', 'Basugaon',
            'Bijni', 'Abhayapuri', 'Golet', 'Barpathar', 'Golaghat', 'Dergaon',
            'Bokakhat', 'Sarupathar', 'Moranhat', 'Nazira', 'Sonari', 'Sibsagar',
            'Jhanji', 'Simaluguri', 'Mariani', 'Amguri', 'Chabua', 'Duliajan',
            'Digboi', 'Margherita', 'Doom Dooma', 'Makum', 'Sadiya', 'Tinsukia',
            'Biswanath Chariali', 'Gohpur', 'Bihpuria', 'Narayanpur', 'Dhemaji',
            'Silapathar', 'Jonai', 'Sibsagar', 'Majuli', 'Jorhat', 'Titabar',
            'Marigaon', 'Jagiroad', 'Nellie', 'Lumding', 'Hojai', 'Lanka',
            'Haflong', 'Maibong', 'Bokajan', 'Sarihajan', 'Hamren', 'Baithalangso',
        ],
        'Bihar' => [
            'Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Purnia', 'Darbhanga',
            'Bihar Sharif', 'Arrah', 'Begusarai', 'Chapra', 'Sasaram', 'Munger',
            'Saharsa', 'Hajipur', 'Samastipur', 'Motihari', 'Siwan', 'Kishanganj',
            'Jamalpur', 'Buxar', 'Jehanabad', 'Aurangabad', 'Nawada', 'Bettiah',
            'Supaul', 'Madhubani', 'Katihar', 'Banka', 'Lakhisarai', 'Sheikhpura',
            'Nalanda', 'Khagaria', 'Araria', 'Forbesganj', 'Madhepura', 'Sitamarhi',
            'Sheohar', 'Gopalganj', 'Maharajganj', 'Barauli', 'Mirganj', 'Raxaul',
            'Bagaha', 'Ramnagar', 'Narkatiaganj', 'Chanpatia', 'Laheriasarai', 'Benipatti',
            'Jhanjharpur', 'Phulparas', 'Biraul', 'Kusheshwar Asthan', 'Benipur', 'Alamnagar',
            'Manihari', 'Sahibganj', 'Barari', 'Korha', 'Pothia', 'Raniganj',
            'Dalsinghsarai', 'Ujiarpur', 'Teghra', 'Rosera', 'Bachhwara', 'Barauni',
            'Shahpur', 'Koilwar', 'Bihta', 'Paliganj', 'Masaurhi', 'Digha',
            'Fatuha', 'Bakhtiarpur', 'Athmalgola', 'Belchi', 'Islampur', 'Hilsa',
            'Ekangarsarai', 'Rajgir', 'Pawapuri', 'Silao', 'Giriak', 'Sarmera',
            'Barbigha', 'Barhiya', 'Mokama', 'Barh', 'Atha', 'Punpun',
            'Naubatpur', 'Maner', 'Dinapore', 'Danapur', 'Phulwari Sharif', 'Saidpur',
        ],
        'Chhattisgarh' => [
            'Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Durg', 'Rajnandgaon', 'Raigarh',
            'Jagdalpur', 'Ambikapur', 'Mahasamund', 'Dhamtari', 'Bhatapara', 'Kawardha',
            'Balod', 'Baloda Bazar', 'Bemetara', 'Janjgir', 'Sakti', 'Mungeli',
            'Pandariya', 'Lormi', 'Takhatpur', 'Masturi', 'Bilha', 'Kota',
            'Pendra', 'Marwahi', 'Kargi Road', 'Kharod', 'Baradwar', 'Champa',
            'Korba', 'Katghora', 'Pali', 'Manendragarh', 'Baikunthpur', 'Surajpur',
            'Surguja', 'Sitapur', 'Ramanujganj', 'Premnagar', 'Bharatpur', 'Jashpur',
            'Pathalgaon', 'Bagicha', 'Kunkuri', 'Duldula', 'Kansabel', 'Sanna',
            'Narayanpur', 'Bijapur', 'Dantewada', 'Sukma', 'Konta', 'Bhopalpattnam',
            'Usur', 'Bokaband', 'Bastanar', 'Tokapal', 'Bade Rajpur', 'Chitrakot',
            'Arang', 'Tilda', 'Sirrari', 'Deori', 'Bhatgaon', 'Pithora',
            'Basna', 'Pipariya', 'Kharora', 'Mandir Hasaud', 'Kurud', 'Magarlod',
            'Sihawa', 'Gariaband', 'Mainpur', 'Chhura', 'Deobhog', 'Singhora',
        ],
        'Goa' => [
            'Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda', 'Bicholim',
            'Curchorem', 'Sanquelim', 'Valpoi', 'Canacona', 'Cuncolim', 'Quepem',
            'Assolna', 'Benaulim', 'Calangute', 'Candolim', 'Carambolim', 'Cortalim',
            'Curtorim', 'Dabolim', 'Goa Velha', 'Guirim', 'Loutolim', 'Mandrem',
            'Moira', 'Navelim', 'Neura', 'Old Goa', 'Parra', 'Penha de Franca',
            'Pilerne', 'Raia', 'Saligao', 'Sangolda', 'Santa Cruz', 'São José de Areal',
            'Siolim', 'Taleigao', 'Verna', 'Vidyanagar', 'Arambol', 'Anjuna',
            'Baga', 'Betalbatim', 'Bogmalo', 'Calangute', 'Candolim', 'Colva',
            'Dona Paula', 'Majorda', 'Miramar', 'Morjim', 'Palolem', 'Sinquerim',
            'Utorda', 'Vagator', 'Varca', 'Velsao',
        ],
        'Gujarat' => [
            'Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar',
            'Junagadh', 'Gandhinagar', 'Anand', 'Nadiad', 'Morbi', 'Mehsana',
            'Bharuch', 'Navsari', 'Bhuj', 'Palanpur', 'Porbandar', 'Gandhidham',
            'Surendranagar', 'Valsad', 'Amreli', 'Botad', 'Dahod', 'Godhra',
            'Himatnagar', 'Patan', 'Veraval', 'Modasa', 'Kalol', 'Gandhinagar',
            'Viramgam', 'Dholka', 'Sanand', 'Bavla', 'Dhandhuka', 'Dhrangadhra',
            'Halvad', 'Sidhpur', 'Kadi', 'Kheralu', 'Unjha', 'Visnagar',
            'Vadnagar', 'Chanasma', 'Harij', 'Sami', 'Santalpur', 'Deesa',
            'Deodar', 'Dhanera', 'Palanpur', 'Tharad', 'Vadgam', 'Bhabhar',
            'Mansa', 'Gandhinagar', 'Kalol', 'Kheralu', 'Mansa', 'Vadnagar',
            'Unava', 'Satlasana', 'Vijapur', 'Mehsana', 'Becharaji', 'Kadi',
            'Mandvi', 'Mundra', 'Anjar', 'Bhachau', 'Rapar', 'Nakhatrana',
            'Lakhpat', 'Abdasa', 'Bhuj', 'Gandhidham', 'Adipur', 'Kutch',
            'Khambhalia', 'Jamnagar', 'Kalavad', 'Jodiya', 'Dhrol', 'Bhanvad',
            'Okha', 'Dwarka', 'Porbandar', 'Ranavav', 'Kutiyana', 'Mangrol',
            'Keshod', 'Manavadar', 'Vanthali', 'Junagadh', 'Visavadar', 'Bhesana',
            'Talala', 'Una', 'Kodinar', 'Sutrapada', 'Patan', 'Chanasma',
            'Siddhpur', 'Radhanpur', 'Santalpur', 'Vadgam', 'Palanpur', 'Dhanera',
            'Shankheshwar', 'Sami', 'Harij', 'Vadali', 'Sirohi', 'Abu Road',
            'Saputara', 'Ahwa', 'Waghai', 'Dang', 'Vansda', 'Chikhli',
            'Gandevi', 'Bilimora', 'Navsari', 'Jalalpore', 'Mahuva', 'Talaja',
            'Palitana', 'Shihor', 'Gariyadhar', 'Rajula', 'Jafrabad', 'Chalala',
            'Dhari', 'Babra', 'Lilia', 'Lathi', 'Khambha', 'Liliya',
            'Savarkundla', 'Botad', 'Barwala', 'Ranpur', 'Dhandhuka', 'Bavla',
            'Sanand', 'Viramgam', 'Mandal', 'Detroj', 'Dasada', 'Lakhtar',
            'Wadhwan', 'Chotila', 'Sayla', 'Chuda', 'Limbdi', 'Thangadh',
            'Patdi', 'Bamanbore', 'Muli', 'Surendranagar', 'Halvad', 'Dhrangadhra',
        ],
        'Haryana' => [
            'Chandigarh', 'Faridabad', 'Gurugram', 'Panipat', 'Ambala', 'Karnal',
            'Sonipat', 'Yamunanagar', 'Rohtak', 'Hisar', 'Panchkula', 'Bhiwani',
            'Rewari', 'Sirsa', 'Kaithal', 'Jind', 'Kurukshetra', 'Bahadurgarh',
            'Fatehabad', 'Palwal', 'Hodal', 'Tohana', 'Barwala', 'Ellenabad',
            'Rania', 'Dabwali', 'Sirsa', 'Fatehabad', 'Tohana', 'Ratia',
            'Jakhal', 'Uklana', 'Barwala', 'Bhattu', 'Hisar', 'Adampur',
            'Balsamand', 'Hansi', 'Narnaund', 'Bawal', 'Kosli', 'Mahendragarh',
            'Narnaul', 'Ateli', 'Kanina', 'Satnali', 'Rewari', 'Bawal',
            'Pataudi', 'Farrukhnagar', 'Manesar', 'Gurugram', 'Sohna', 'Taoru',
            'Nuh', 'Punahana', 'Ferozepur Jhirka', 'Nagina', 'Hasanpur', 'Palwal',
            'Hathin', 'Hodal', 'Ballabhgarh', 'Faridabad', 'Badkhal', 'Tigaon',
            'Rohtak', 'Meham', 'Sampla', 'Lakhan Majra', 'Kosli', 'Beri',
            'Jhajjar', 'Dadu', 'Matail', 'Salhawas', 'Bahadurgarh', 'Bawana',
            'Sonipat', 'Gohana', 'Gannaur', 'Samalkha', 'Panipat', 'Madlauda',
            'Israna', 'Karnal', 'Nilokheri', 'Indri', 'Gharaunda', 'Assandh',
            'Safidon', 'Jind', 'Uchana', 'Julana', 'Narwana', 'Tohana',
            'Kurukshetra', 'Thanesar', 'Pehowa', 'Shahabad', 'Ladwa', 'Babain',
            'Ambala', 'Barara', 'Naraingarh', 'Sadhaura', 'Jagadhri', 'Bilaspur',
            'Radaur', 'Yamunanagar', 'Chhachhrauli', 'Panchkula', 'Kalka', 'Pinjore',
            'Raipur Rani', 'Morni', 'Bhiwani', 'Loharu', 'Siwani', 'Tosham',
            'Bawani Khera', 'Charkhi Dadri', 'Badhra', 'Bond', 'Jui Khurd',
        ],
        'Himachal Pradesh' => [
            'Shimla', 'Dharamshala', 'Mandi', 'Solan', 'Kullu', 'Manali', 'Hamirpur',
            'Bilaspur', 'Palampur', 'Nahan', 'Sundarnagar', 'Chamba', 'Kangra', 'Una',
            'Dalhousie', 'McLeod Ganj', 'Kasauli', 'Parwanoo', 'Baddi', 'Paonta Sahib',
            'Rohru', 'Jubbal', 'Kotkhai', 'Theog', 'Rampur', 'Kumarsain', 'Narkanda',
            'Kotgarh', 'Chaupal', 'Cheog', 'Seoni', 'Shimla Rural', 'Kasumpti',
            'Mashobra', 'Kufri', 'Fagu', 'Chail', 'Kandaghat', 'Arki', 'Kunihar',
            'Darlaghat', 'Shalaghat', 'Ramshehar', 'Bharari', 'Junga', 'Bagthan',
            'Solan', 'Kasauli', 'Dharampur', 'Kumarhatti', 'Dagshai', 'Subathu',
            'Bilaspur', 'Ghumarwin', 'Jhanduta', 'Naina Devi', 'Bharari', 'Sri Naina',
            'Kallar', 'Gumanu', 'Bamta', 'Bharoli', 'Sariun', 'Luhnu',
            'Hamirpur', 'Barsar', 'Nadaun', 'Amb', 'Bijhari', 'Galore',
            'Tauni Devi', 'Sujanpur', 'Tira Sujanpur', 'Bhota', 'Jahru', 'Lambloo',
            'Dharamshala', 'Kangra', 'Palampur', 'Baijnath', 'Joginder Nagar',
            'Nurpur', 'Indora', 'Fatehpur', 'Jawalamukhi', 'Dehra Gopipur',
            'Dera Baba', 'Nagrota Bagwan', 'Nagrota Surian', 'Shahpur', 'Rakkar',
            'Sansarpur', 'Gaggal', 'Kangra', 'Khundian', 'Bhawanathpur', 'Alampur',
            'Mandi', 'Sundarnagar', 'Joginder Nagar', 'Padhar', 'Baldi', 'Karsog',
            'Chachyot', 'Kotli', 'Dharmpur', 'Baidyanath', 'Mandi', 'Rewalsar',
            'Prashar', 'Janjehli', 'Sarahan', 'Karsog', 'Chandigarh', 'Bharari',
            'Kullu', 'Manali', 'Bhuntar', 'Banjar', 'Anni', 'Nirmand',
            'Jalori Pass', 'Shoja', 'Jibhi', 'Kheerganga', 'Kasol', 'Manikaran',
            'Naggar', 'Raison', 'Kothi', 'Solang', 'Palchan', 'Katrain',
            'Larji', 'Sainj', 'Tirthan', 'Chamba', 'Dalhousie', 'Bharmour',
            'Churah', 'Salooni', 'Holi', 'Bhatiyat', 'Tisa', 'Pukhri',
            'Mehla', 'Kiari', 'Chamba', 'Saho', 'Manimahesh', 'Kugti',
            'Una', 'Amb', 'Bangana', 'Daulatpur', 'Gagret', 'Haroli',
            'Santokhgarh', 'Mehatpur', 'Bharwain', 'Saloh', 'Una', 'Tahliwala',
        ],
        'Jharkhand' => [
            'Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar', 'Hazaribagh',
            'Giridih', 'Ramgarh', 'Dumka', 'Phusro', 'Chirkunda', 'Madhupur',
            'Sahibganj', 'Pakur', 'Godda', 'Chaibasa', 'Jhumri Telaiya', 'Simdega',
            'Gumla', 'Lohardaga', 'Latehar', 'Garhwa', 'Chatra', 'Koderma',
            'Bishrampur', 'Jaridih', 'Gomia', 'Bermo', 'Chandrapura', 'Kandra',
            'Sini', 'Adityapur', 'Mango', 'Jugsalai', 'Bagbera', 'Gamharia',
            'Rajnagar', 'Jama', 'Jarmundi', 'Ramgarh', 'Mandu', 'Patratu',
            'Barkagaon', 'Jarwa', 'Bishnugarh', 'Barkatha', 'Ichak', 'Katkamdag',
            'Katkamsandi', 'Ormanjhi', 'Angara', 'Chanho', 'Bero', 'Itki',
            'Lapung', 'Mandar', 'Namkum', 'Kanke', 'Ratu', 'Burmu',
            'Khelari', 'Silli', 'Sonahatu', 'Tamad', 'Khunti', 'Karra',
            'Murhu', 'Rania', 'Torpa', 'Basia', 'Kamdara', 'Sisai',
            'Bhandra', 'Bagicha', 'Lohardaga', 'Kuru', 'Kairo', 'Kisko',
            'Senha', 'Kuchai', 'Bero', 'Mandar', 'Angara', 'Rahe',
            'Patamda', 'Ghatshila', 'Musabani', 'Dhalbhumgarh', 'Dumaria', 'Baharagora',
            'Chakulia', 'Jhinkpani', 'Chakradharpur', 'Kharsawan', 'Saraikela',
            'Rajkharsawan', 'Chandil', 'Ichagarh', 'Kukru', 'Nimdih', 'Adityapur',
        ],
        'Karnataka' => [
            'Bengaluru', 'Mysuru', 'Hubballi', 'Mangaluru', 'Belagavi', 'Davangere',
            'Ballari', 'Tumakuru', 'Shivamogga', 'Raichur', 'Bidar', 'Hospet',
            'Gulbarga', 'Udupi', 'Hassan', 'Chitradurga', 'Robertson Pet',
            'Gadag-Betageri', 'Mandya', 'Chikkamagaluru', 'Dharwad', 'Haveri',
            'Kolar', 'Robertsonpet', 'Ranebennuru', 'Chamarajanagara', 'Kolar Gold Fields',
            'Ramanagara', 'Bhadravati', 'Chintamani', 'Karwar', 'Gokak', 'Sirsi',
            'Sindhagi', 'Kumta', 'Bailhongal', 'Shahabad', 'Gadag', 'Sira',
            'Sakleshpur', 'Tiptur', 'Hunsur', 'Kollegal', 'Nanjangud', 'Puttur',
            'Kushalanagara', 'Virajpet', 'Madikeri', 'Somwarpet', 'Piriyapatna',
            'Krishnarajanagara', 'Heggadadevanakote', 'Kolar', 'Mulbagal', 'Malur',
            'Bangarapet', 'KGF', 'Srinivasapur', 'Gauribidanur', 'Chikkaballapura',
            'Bagepalli', 'Gudibanda', 'Shidlaghatta', 'Chintamani', 'Mudigere',
            'Narasimharajapura', 'Koppa', 'Sringeri', 'Chikmagalur', 'Tarikere',
            'Kadur', 'Birur', 'Ajjampura', 'Hosadurga', 'Holalkere', 'Hiriyur',
            'Molakalmuru', 'Challakere', 'Jagaluru', 'Kottur', 'Hospet', 'Sandur',
            'Kudligi', 'Hagaribommanahalli', 'Harapanahalli', 'Hadagalli', 'Vijayanagara',
            'Siraguppa', 'Kampli', 'Kushtagi', 'Yelbarga', 'Kanakagiri', 'Gangavathi',
            'Sindhanur', 'Maski', 'Manvi', 'Lingsugur', 'Devadurga', 'Kalmala',
            'Mudgal', 'Hatti', 'Shahpur', 'Shorapur', 'Yadgir', 'Gurumitkal',
            'Chittapur', 'Sedam', 'Chincholi', 'Kamalapur', 'Afzalpur', 'Jewargi',
            'Shahabad', 'Wadi', 'Chitapur', 'Malkapur', 'Basavakalyan', 'Bhalki',
            'Aurad', 'Humnabad', 'Basavana Bagevadi', 'Indi', 'Sindgi', 'Muddebihal',
            'Vijayapura', 'Mamadapur', 'Almatti', 'Athani', 'Bailhongal', 'Chikodi',
            'Gokak', 'Hukkeri', 'Kittur', 'Khanapur', 'Londa', 'Parasgad',
            'Ramdurg', 'Raybag', 'Saundatti', 'Sampagaon', 'Nipani', 'Sadalga',
            'Mudalagi', 'Yaragatti', 'Dharwad', 'Hubli', 'Navalgund', 'Kalghatgi',
            'Kundgol', 'Alnavar', 'Annigeri', 'Mundagod', 'Shirhatti', 'Naragund',
            'Ron', 'Gadag', 'Lakshmeshwar', 'Mulgund', 'Naregal', 'Haliyal',
            'Yellapur', 'Mundgod', 'Kallagundi', 'Bhatkal', 'Honnavara', 'Kumta',
            'Siddapura', 'Sirsi', 'Ankola', 'Karwar', 'Dandeli', 'Joida',
            'Udupi', 'Kundapura', 'Karkala', 'Shankaranarayana', 'Brahmavara',
            'Hangal', 'Hirekerur', 'Ranebennur', 'Savanur', 'Byadgi', 'Akkialur',
            'Rattihalli', 'Channagiri', 'Holalkere', 'Homali', 'Davangere',
            'Harihar', 'Jagalur', 'Mayakonda', 'Nyamathi', 'Santhebennur',
            'Shimoga', 'Bhadravati', 'Sagar', 'Shikaripur', 'Soraba', 'Hosanagara',
            'Kargal', 'Ayanur', 'Beltangady', 'Karkala', 'Mudabidri', 'Mangaluru',
            'Ullal', 'Kotekar', 'Bajpe', 'Mulki', 'Padubidri', 'Surathkal',
            'Puttur', 'Sulya', 'Vittla', 'Kadaba', 'Punjalkatte', 'Bantwal',
            'Thumbe', 'Kannur', 'Moodabidri', 'Hassan', 'Channarayapatna', 'Holenarsipur',
            'Arkalgud', 'Sakleshpur', 'Belur', 'Alur', 'Beltangadi', 'Sulya',
            'Kodagu', 'Madikeri', 'Somwarpet', 'Virajpet', 'Ponnampet', 'Kushalanagara',
        ],
        'Kerala' => [
            'Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Thrissur', 'Alappuzha', 'Kollam',
            'Palakkad', 'Kannur', 'Kottayam', 'Malappuram', 'Kasaragod', 'Pathanamthitta',
            'Idukki', 'Wayanad', 'Munnar', 'Kochi', 'Kakkanad', 'Tripunithura',
            'Ernakulam', 'Angamaly', 'Perumbavoor', 'Aluva', 'Kothamangalam', 'Muvattupuzha',
            'Thrippunithura', 'Maradu', 'Thrikkakara', 'Edapally', 'Vyttila',
            'Palarivattom', 'Kalamassery', 'Cherthala', 'Mavelikara', 'Kayamkulam',
            'Ambalappuzha', 'Haripad', 'Chengannur', 'Mannar', 'Ramankary', 'Champakulam',
            'Kuttanad', 'Edathua', 'Kattanam', 'Bharanikkavu', 'Kollam', 'Karunagappally',
            'Punalur', 'Kottarakara', 'Chavara', 'Paravur', 'Kundara', 'Anchal',
            'Pathanapuram', 'Kadakkavoor', 'Varkala', 'Attingal', 'Nedumangad',
            'Chirayinkeezhu', 'Kazhakootam', 'Technopark', 'Thirumala', 'Peyad',
            'Vizhinjam', 'Kovalam', 'Neyyattinkara', 'Parassala', 'Kattakada',
            'Vellanad', 'Vithura', 'Tholicode', 'Kallara', 'Chadayamangalam',
            'Kottayam', 'Changanassery', 'Pala', 'Vaikom', 'Kanjirappally',
            'Erattupetta', 'Mundakayam', 'Ponnala', 'Karukachal', 'Kaduthuruthy',
            'Kurupanthara', 'Manarcad', 'Ettumanoor', 'Koothattukulam', 'Piravom',
            'Thodupuzha', 'Moolamattom', 'Vandippath', 'Idukki', 'Kattappana',
            'Adimaly', 'Nedumkandam', 'Rajakkad', 'Devikulam', 'Kumily', 'Thekkady',
            'Vagamon', 'Kuttampuzha', 'Kothamangalam', 'Aluva', 'Ernakulam',
            'Muvattupuzha', 'Kunnathunad', 'Alangad', 'Chowara', 'Kadavanthra',
            'Kochi', 'Mattancherry', 'Fort Kochi', 'Vypin', 'Cherai', 'Kuzhuppilly',
            'Edavanakkad', 'Kodungallur', 'Thrissur', 'Irinjalakuda', 'Chalakudy',
            'Kodungallur', 'Guruvayur', 'Kunnamkulam', 'Wadakkancherry', 'Pattambi',
            'Cheruthuruthy', 'Shoranur', 'Ottappalam', 'Mannarkkad', 'Palakkad',
            'Chittur', 'Alathur', 'Nemmara', 'Kollengode', 'Koduvayur', 'Kozhinjampara',
            'Malappuram', 'Manjeri', 'Tirur', 'Ponnani', 'Nilambur', 'Perinthalmanna',
            'Kottakkal', 'Kondotty', 'Edappal', 'Tavanur', 'Kuttippuram', 'Valanchery',
            'Makkaraparamba', 'Vengara', 'Areekode', 'Pulpally', 'Mananthavady',
            'Kalpetta', 'Sulthan Bathery', 'Vythiri', 'Meppadi', 'Kozhikode',
            'Koyilandy', 'Vatakara', 'Thamarassery', 'Balussery', 'Koduvally',
            'Mukkam', 'Kunnamangalam', 'Nadapuram', 'Payyoli', 'Perambra',
            'Kannur', 'Thalassery', 'Koothuparamba', 'Payyanur', 'Taliparamba',
            'Mattannur', 'Iritty', 'Kuthuparamba', 'Pappinisseri', 'Dharmadom',
            'Kannapuram', 'Cherukunnu', 'Pazhayangadi', 'Peravoor', 'Mananthavady',
            'Kasaragod', 'Kanhangad', 'Nileshwar', 'Manjeshwar', 'Uppala',
            'Kumbla', 'Mulleria', 'Mogralputhur', 'Badiadka', 'Delampady',
        ],
        'Madhya Pradesh' => [
            'Bhopal', 'Indore', 'Jabalpur', 'Gwalior', 'Ujjain', 'Sagar', 'Dewas',
            'Satna', 'Ratlam', 'Rewa', 'Murwara', 'Singrauli', 'Burhanpur', 'Khandwa',
            'Morena', 'Bhind', 'Chhindwara', 'Guna', 'Damoh', 'Mandsaur', 'Baidhan',
            'Balaghat', 'Betul', 'Hoshangabad', 'Itarsi', 'Katiya', 'Khajuraho',
            'Maihar', 'Nagda', 'Neemuch', 'Pithampur', 'Sehore', 'Seoni', 'Shahdol',
            'Shivpuri', 'Tikamgarh', 'Vidisha', 'Ashok Nagar', 'Barwani', 'Chhatarpur',
            'Datia', 'Dhar', 'Ganj Basoda', 'Harsud', 'Harda', 'Khandwa',
            'Maksi', 'Mandideep', 'Mhow', 'Multai', 'Narsinghpur', 'Tarana',
            'Umaria', 'Panagar', 'Panna', 'Raisen', 'Rajgarh', 'Raghogarh',
            'Rehli', 'Sanawad', 'Sarangpur', 'Shajapur', 'Shamgarh', 'Sheopur',
            'Shujalpur', 'Sironj', 'Tendu Kheda', 'Tikamgarh', 'Timarni', 'Vidisha',
            'Jaora', 'Jhabua', 'Jobat', 'Kannod', 'Khargone', 'Khetia',
            'Kirnapur', 'Kotma', 'Kurwai', 'Lateri', 'Maharajpur', 'Mahidpur',
            'Majholi', 'Makdon', 'Malhargarh', 'Manasa', 'Manawar', 'Mandleshwar',
            'Mauganj', 'Nagod', 'Naigarhi', 'Nainpur', 'Nasrullaganj', 'Nateran',
            'Nepanagar', 'Niwari', 'Nowgaon', 'Narsinghgarh', 'Orchha', 'Pachmarhi',
            'Pandhana', 'Pandhurna', 'Parasia', 'Patan', 'Pathariya', 'Pawai',
            'Petlawad', 'Prabhat Pattan', 'Punasa', 'Pushprajgarh', 'Rahatgarh',
            'Ramnagar', 'Rampur Naikin', 'Ranapur', 'Sabalgarh', 'Sagar', 'Sailana',
            'Sanchi', 'Sanwer', 'Sarangpur', 'Satna', 'Sausar', 'Sehore',
            'Sendhwa', 'Shahdol', 'Shahganj', 'Shahpur', 'Shajapur', 'Shamli',
            'Shivpuri', 'Shujalpur', 'Sidhi', 'Silwani', 'Singrauli', 'Sironj',
            'Sohagpur', 'Susner', 'Tal', 'Talen', 'Tarana', 'Tendukheda',
            'Teonthar', 'Thandla', 'Tikamgarh', 'Timarni', 'Udaipura', 'Ujjain',
            'Umaria', 'Unchehara', 'Vijayraghavgarh', 'Vidisha',
        ],
        'Maharashtra' => [
            'Mumbai', 'Pune', 'Nagpur', 'Thane', 'Nashik', 'Aurangabad', 'Solapur',
            'Kolhapur', 'Amravati', 'Navi Mumbai', 'Sangli', 'Malegaon', 'Jalgaon',
            'Akola', 'Latur', 'Ahmednagar', 'Dhule', 'Chandrapur', 'Parbhani',
            'Ichalkaranji', 'Jalna', 'Nanded', 'Wardha', 'Satara', 'Ratnagiri',
            'Miraj', 'Pimpri Chinchwad', 'Panvel', 'Ulhasnagar', 'Bhiwandi', 'Vasai',
            'Virar', 'Kalyan', 'Dombivli', 'Mira-Bhayandar', 'Thane', 'Palghar',
            'Badlapur', 'Ambernath', 'Kulgaon', 'Murbad', 'Karjat', 'Pen',
            'Alibag', 'Murud', 'Roha', 'Mahad', 'Shrivardhan', 'Mhasla',
            'Poladpur', 'Sudhagad', 'Tala', 'Panvel', 'Uran', 'Khopoli',
            'Khalapur', 'Rajgurunagar', 'Junnar', 'Ambegaon', 'Shirur', 'Khed',
            'Maval', 'Mulshi', 'Velhe', 'Bhor', 'Purandar', 'Baramati',
            'Indapur', 'Daund', 'Shrigonda', 'Karjat', 'Jamkhed', 'Shevgaon',
            'Pathardi', 'Shrigonda', 'Newasa', 'Sheogaon', 'Nagar', 'Rahuri',
            'Shirdi', 'Kopargaon', 'Sangamner', 'Akole', 'Nashik', 'Igatpuri',
            'Trimbak', 'Peth', 'Surgana', 'Kalwan', 'Deola', 'Baglan',
            'Malegaon', 'Nandgaon', 'Chandwad', 'Dindori', 'Peint', 'Sinnar',
            'Niphad', 'Yeola', 'Manmad', 'Satana', 'Dhule', 'Shirpur',
            'Sindkheda', 'Sakri', 'Kusumba', 'Jalgaon', 'Chalisgaon', 'Pachora',
            'Jamner', 'Bhusawal', 'Yawal', 'Raver', 'Sawda', 'Muktainagar',
            'Bodwad', 'Malkapur', 'Chikhali', 'Amravati', 'Achalpur', 'Warud',
            'Paratwada', 'Anjangaon', 'Daryapur', 'Murtizapur', 'Akola', 'Akot',
            'Balapur', 'Patur', 'Barshitakli', 'Telhara', 'Washim', 'Mangrulpir',
            'Karanja', 'Manora', 'Risod', 'Malegaon', 'Buldhana', 'Khamgaon',
            'Chikhli', 'Deulgaon Raja', 'Mehkar', 'Sindkhed Raja', 'Lonar', 'Nandura',
            'Motala', 'Jalna', 'Ambad', 'Badnapur', 'Bhokardan', 'Jafrabad',
            'Parbhani', 'Gangakhed', 'Sonpeth', 'Pathri', 'Manwath', 'Palam',
            'Selu', 'Jintur', 'Hingoli', 'Aundha Nagnath', 'Kalamnuri', 'Sengaon',
            'Basmath', 'Nanded', 'Himayatnagar', 'Biloli', 'Deglur', 'Mukhed',
            'Kandhar', 'Loha', 'Bhokar', 'Naigoan', 'Dharmabad', 'Umri',
            'Islapur', 'Pusad', 'Umarkhed', 'Kinwat', 'Mahagaon', 'Wani',
            'Yavatmal', 'Darwha', 'Digras', 'Arni', 'Pusad', 'Kalamb',
            'Maregaon', 'Ralegaon', 'Ghatanji', 'Kelapur', 'Wardha', 'Hinganghat',
            'Arvi', 'Deoli', 'Samudrapur', 'Karanja', 'Seloo', 'Amaravati',
            'Narkhed', 'Katol', 'Kalameshwar', 'Savner', 'Parseoni', 'Ramtek',
            'Mouda', 'Kamptee', 'Umred', 'Kuhi', 'Bhiwapur', 'Nagpur',
            'Pen', 'Gondia', 'Goregaon', 'Amgaon', 'Salekasa', 'Sadanapalle',
            'Tumsar', 'Tirora', 'Bhandara', 'Pauni', 'Lakhni', 'Sakoli',
            'Lakhandur', 'Mohadi', 'Chandrapur', 'Warora', 'Mul', 'Bhadravati',
            'Ballarpur', 'Pombhurna', 'Sindewahi', 'Bramhapuri', 'Nagbhir',
            'Gadchiroli', 'Aheri', 'Sironcha', 'Etapalli', 'Mulchera', 'Mahagaon',
            'Kurkheda', 'Dhanora', 'Chamorshi', 'Armori', 'Desaiganj',
            'Ratnagiri', 'Sangmeshwar', 'Lanja', 'Rajapur', 'Khed', 'Chiplun',
            'Guhagar', 'Dapoli', 'Mandangad', 'Sindhudurg', 'Malvan', 'Devgad',
            'Kankavli', 'Vaibhavwadi', 'Sawantwadi', 'Dodamarg', 'Vengurla',
            'Osmanabad', 'Tuljapur', 'Tuljapur', 'Bhoom', 'Paranda', 'Kallam',
            'Umarga', 'Latur', 'Ahmadpur', 'Chakur', 'Deoni', 'Shirur Anantpal',
            'Ausa', 'Jalkot', 'Nilanga', 'Renapur', 'Solapur', 'Mohol',
            'Pandharpur', 'Mangalwedha', 'Madha', 'Karmala', 'Barshi', 'Akkalkot',
            'South Solapur', 'Malshiras', 'Sangola', 'Kavathemahankal', 'Jath',
            'Atpadi', 'Tasgaon', 'Palus', 'Kadegaon', 'Wai', 'Mahabaleshwar',
            'Khandala', 'Patan', 'Karad', 'Satara', 'Jaoli', 'Mahabaleshwar',
            'Shahuwadi', 'Panhala', 'Hatkanangle', 'Shirol', 'Kagal', 'Bavda',
            'Gaganbawada', 'Radhanagari', 'Bhudargad', 'Ajra', 'Chandgad',
            'Gadhinglaj', 'Kolhapur', 'Karvir', 'Panhala', 'Shahuwadi',
        ],
        'Manipur' => [
            'Imphal', 'Bishnupur', 'Churachandpur', 'Thoubal', 'Kakching', 'Ukhrul',
            'Senapati', 'Tamenglong', 'Jiribam', 'Lilong', 'Moirang', 'Mayang Imphal',
            'Wangkhei', 'Porompat', 'Keirao', 'Andro', 'Nambol', 'Oinam',
            'Kumbi', 'Ningthoukhong', 'Bishnupur', 'Nambol', 'Yairipok', 'Sugnu',
            'Kakching Khunou', 'Lilong', 'Heirok', 'Wabagai', 'Wangjing', 'Thoubal',
            'Chandel', 'Moreh', 'Tengnoupal', 'Machil', 'Kamjong', 'Phungyar',
            'Ukhrul', 'Lungwa', 'Shamchalai', 'Mao', 'Tadubi', 'Maram',
            'Puranikachar', 'Saitu', 'Kangpokpi', 'Motbung', 'Tamenglong',
            'Tamei', 'Tousem', 'Nungba', 'Longmai', 'Laiwang', 'Phailen',
            'Jiribam', 'Borobekra', 'Jiri', 'Churachandpur', 'Sangaikot',
            'Singngat', 'Tuibui', 'Thanlon', 'Henglep', 'Lungtan',
            'Pherzawl', 'Tipaimukh', 'Pariong', 'Vangai', 'Bairabi',
        ],
        'Meghalaya' => [
            'Shillong', 'Tura', 'Nongstoin', 'Jowai', 'Baghmara', 'Williamnagar',
            'Mawlai', 'Nongpoh', 'Mairang', 'Cherrapunji', 'Pynursla', 'Mawkyrwat',
            'Mawphlang', 'Smit', 'Mawkynrew', 'Mawshynrut', 'Mawthadraishan',
            'Umling', 'Nongstoin', 'Nonglang', 'Rambrai', 'Mawthadraishan',
            'Mawkre', 'Riangdo', 'Rambrai', 'Umdor', 'Umsning', 'Nongpoh',
            'Umling', 'Mawpran', 'Mawbri', 'Mawiong', 'Mawlyndep', 'Mawblang',
            'Mawsynram', 'Shella', 'Laitkor', 'Mawkynrum', 'Mawpun', 'Mawrang',
            'Mylliem', 'Langkyrdem', 'Pynursla', 'Mawkasi', 'Mawdon', 'Mawphanlur',
            'Khliehriat', 'Khliehshnong', 'Mupar', 'Lad Rymbai', 'Dawki',
            'Mohanpur', 'Mawhati', 'Rangshken', 'Bholaganj', 'Balat', 'Raliang',
            'Jowai', 'Shangpung', 'Thadlaskein', 'Karbi', 'Ummulong', 'Sakwang',
            'Mendipathar', 'Dobasipara', 'Chibinang', 'Phulbari', 'Bajengdoba',
            'Resubelpara', 'Dadenggre', 'Bibra', 'Damra', 'Gambegre',
            'Wajad', 'Gasuapara', 'Siju', 'Rangsakona', 'Kherapara',
            'Selsella', 'Zikzak', 'Baghmara', 'Chokpot', 'Bhalukaghat',
            'Sibbari', 'Dalu', 'Betasing', 'Rongara', 'Mahendraganj',
            'Bhaitbari', 'Tikrikilla', 'Phulbari', 'Tura', 'Dadenggre',
            'Gambegre', 'Rajabala', 'Mendipathar', 'Dalu', 'Mahendraganj',
            'Rongjeng', 'Anogre', 'Songsak', 'Samanda', 'Dihe', 'Adokgre',
            'Bakdang', 'Dobasipara', 'Chitmang', 'Gajubagan', 'Bakenang',
            'Moinagiri', 'Rompa', 'Rongkhon', 'Rongmil', 'Nardang',
            'Asanang', 'Simsang', 'Nengkhra', 'Old Burberry', 'Pura',
        ],
        'Mizoram' => [
            'Aizawl', 'Lunglei', 'Champhai', 'Serchhip', 'Kolasib', 'Lawngtlai',
            'Saiha', 'Mamit', 'Khawzawl', 'Hnahthial', 'Darlawn', 'Sairang',
            'Seling', 'Phaileng', 'Thenzawl', 'Saitual', 'N. Vanlaiphai',
            'Khawhai', 'Vairengte', 'Hlimen', 'Sihphir', 'Chhingchhip',
            'Zotlang', 'Lengpui', 'Bairabi', 'Kawrthah', 'Kawnpui',
            'Lunglei', 'Hnahthial', 'S. Vanlaiphai', 'Lungdai', 'Zawlnuam',
            'West Phaileng', 'Silsuri', 'Kawrthah', 'Lungdar', 'Ngopa',
            'Sialdawi', 'Sairep', 'Pangzawl', 'Hrangchalkawn', 'Ratu',
            'Zotlang', 'Serchhip', 'Bungtlang', 'Sangau', 'Tlabung',
            'Parvatla', 'Farkawn', 'Vaphai', 'Khawbung', 'Murlen',
            'F. S. Khand', 'Khawruhlian', 'Vanzau', 'Bilkhawthlir', 'Phullen',
            'Lungsen', 'Mamit', 'Kanghmun', 'Rengil', 'Ratu',
            'Ngopa', 'Darlak', 'Phuaibuang', 'Dultrang', 'Saiha',
            'Tuisih', 'Siago', 'Lopu', 'New Serchhip', 'Hmawngbu',
        ],
        'Nagaland' => [
            'Kohima', 'Dimapur', 'Mokokchung', 'Tuensang', 'Wokha', 'Zunheboto',
            'Mon', 'Phek', 'Kiphire', 'Longleng', 'Peren', 'Chumukedima',
            'Medziphema', 'Niuland', 'Agohoto', 'Khezhakeno', 'Pfutsero',
            'Sekruzu', 'Wokha', 'Bhandari', 'Changpang', 'Sungro', 'Chukitong',
            'Mokokchung', 'Tsemenyu', 'Ongpangkong', 'Sangtamtang', 'Longkhim',
            'Tuensang', 'Noklak', 'Chare', 'Shamatore', 'Thonoknyu', 'Longching',
            'Angjangyang', 'Sotokha', 'Mon', 'Naginsimilar', 'Shangnyu',
            'Chenmoho', 'Mohan', 'Tizit', 'Tamlu', 'Tobu', 'Wakching',
            'Phek', 'Satoi', 'Zuketsa', 'Phukuba', 'Ruzhazho', 'Chizami',
            'Kiphire', 'Pungro', 'Kiusam', 'Sangtam', 'Amahator', 'Longmatra',
            'Zunheboto', 'Khevishe', 'Satoi', 'Suruhoto', 'Sukepu', 'Akuluto',
            'Dimapur', 'Kuhuboto', 'Nihokhu', 'Zubza', 'Viswema', 'Dzuleke',
            'Kidima', 'Mima', 'Porba', 'Changtongya', 'Mopongchuket', 'Japukong',
            'Longsa', 'Lungwa', 'Khongjiri', 'Longleng', 'Tamlu', 'Sangtamtang',
            'Yongnyah', 'Longkhim', 'Kubolong', 'Bare', 'Yachem', 'Noksen',
            'Chingmei', 'Kiphire', 'Kiusam', 'Seyochung', 'Sangphur', 'Pungro',
        ],
        'Odisha' => [
            'Bhubaneswar', 'Cuttack', 'Rourkela', 'Berhampur', 'Sambalpur', 'Puri',
            'Balasore', 'Bhadrak', 'Baripada', 'Jharsuguda', 'Jeypore', 'Barbil',
            'Angul', 'Dhenkanal', 'Kendrapara', 'Paradip', 'Khallikote', 'Chatrapur',
            'Rayagada', 'Phulbani', 'Balangir', 'Bargarh', 'Boudh', 'Deogarh',
            'Gajapati', 'Ganjam', 'Jagatsinghpur', 'Kalahandi', 'Kandhamal', 'Kendrapara',
            'Keonjhar', 'Khurda', 'Koraput', 'Malkangiri', 'Mayurbhanj', 'Nabarangpur',
            'Nayagarh', 'Nuapada', 'Puri', 'Subarnapur', 'Sundergarh', 'Talcher',
            'Jajpur', 'Bhadrak', 'Balasore', 'Baripada', 'Rairangpur', 'Udala',
            'Karanjia', 'Kaptipada', 'Betnoti', 'Rasagobindapur', 'Jharpokharia',
            'Bangriposi', 'Chandua', 'Kuliana', 'Suliapada', 'Baripada',
            'Puri', 'Nimapara', 'Pipili', 'Satyabadi', 'Brahmagiri', 'Kakatpur',
            'Astaranga', 'Konark', 'Gop', 'Delang', 'Chandipur', 'Balasore',
            'Soro', 'Nilgiri', 'Basta', 'Bhograi', 'Jaleswar', 'Remuna',
            'Baliapal', 'Singla', 'Bahanaga', 'Basta', 'Baleshwar', 'Bhadrak',
            'Basudevpur', 'Tihidi', 'Chandbali', 'Dhamnagar', 'Agarpada', 'Bhandari Pokhari',
            'Kendrapara', 'Pattamundai', 'Marsaghai', 'Rajkanika', 'Aul', 'Derabish',
            'Garadpur', 'Mahakalapada', 'Jajpur', 'Bhuban', 'Panikoili', 'Barabati',
            'Jajpur Road', 'Korai', 'Balichandrapur', 'Binjharpur', 'Dasarathapur',
            'Cuttack', 'Jagatsinghpur', 'Pardip', 'Kujanga', 'Balikuda', 'Ersama',
            'Tirtol', 'Biridi', 'Kishannagar', 'Puri', 'Brahmagiri', 'Satyabadi',
            'Pipili', 'Nimapada', 'Kakatpur', 'Astaranga', 'Gop', 'Delanga',
            'Khurda', 'Jatani', 'Bhubaneswar', 'Tangi', 'Chilika', 'Banapur',
            'Begunia', 'Balugaon', 'Nayagarh', 'Khandapada', 'Dasapalla', 'Gania',
            'Ranapur', 'Odagaon', 'Nuagaon', 'Nayagarh Sadar', 'Ganjam', 'Bhanjanagar',
            'Buguda', 'Polasara', 'Kabisuryanagar', 'Purusottampur', 'Khalikote',
            'Chhatrapur', 'Brahmapur', 'Chikiti', 'Digapahandi', 'Patalanga',
            'Hinjilicut', 'Aska', 'Surendranagar', 'Kodala', 'Jarada', 'Sanakhemundi',
            'Koraput', 'Sunabeda', 'Jeypore', 'Kotpad', 'Kundura', 'Pottangi',
            'Nandapur', 'Laxmipur', 'Dasamantapur', 'Malkangiri', 'Kalimela',
            'Khovraguda', 'Mathili', 'Kudumulguma', 'Nabarangpur', 'Ummerkote',
            'Dabugan', 'Papadahandi', 'Khatiguda', 'Boriguma', 'Nabarangpur',
            'Kalahandi', 'Bhawanipatna', 'Kesinga', 'Mukhiguda', 'Dhramgarh',
            'Junagarh', 'Golamunda', 'Jaipatna', 'Thuanmul', 'Narla',
            'Balangir', 'Patnagarh', 'Kantabanji', 'Titlagarh', 'Saintala',
            'Sindhekela', 'Gaisilat', 'Bongamunda', 'Agalpur', 'Belpara',
            'Bargarh', 'Sohela', 'Barapali', 'Bijepur', 'Padmapur', 'Paikamal',
            'Jharbandha', 'Barpali', 'Ambabhona', 'Bhatli', 'Rajborasambar',
            'Sundargarh', 'Rourkela', 'Bondamund', 'Rajgangpur', 'Kutra',
            'Bisra', 'Lathikata', 'Bargaon', 'Tangarpali', 'Hemgiri', 'Brahmani',
            'Sambalpur', 'Burla', 'Hirakud', 'Rengali', 'Govindpur', 'Maneswar',
            'Dhama', 'Bamra', 'Jujomura', 'Naktideul', 'Sambalpur Town',
            'Deogarh', 'Rairakhol', 'Reamal', 'Barkot', 'Tileibani', 'Kundheikola',
            'Boudh', 'Sonepur', 'Binka', 'Tarbha', 'Ullunda', 'Birmaharajpur',
            'Subarnapur', 'Kantamal', 'Khariar', 'Komna', 'Muribahal', 'Sindhekela',
            'Dhenkanal', 'Hindol', 'Kamakhyanagar', 'Talcher', 'Bhuban', 'Parjang',
            'Kankadahad', 'Barki', 'Balipatna', 'Makanpur', 'Angul', 'Athmallik',
            'Kishorenagar', 'Bantala', 'Palalahada', 'Chhendipada', 'Nalco',
            'Banarpal', 'Talcher', 'Khandabandh', 'Pallahada', 'Keonjhar', 'Anandapur',
            'Jhumpura', 'Ghatgaon', 'Harichandanpur', 'Barbil', 'Turumung',
            'Telkoi', 'Kuanr', 'Bamebari', 'Champua', 'Patna', 'Kendujhar',
            'Mayurbhanj', 'Baripada', 'Udala', 'Rairangpur', 'Karanjia', 'Betnoti',
            'Kaptipada', 'Rasagobindapur', 'Suliapada', 'Kolian', 'Mahuldiha',
            'Bisoi', 'Jamda', 'Kusuli', 'Tiring', 'Bahalda', 'Rairangpur',
            'Chandua', 'Bangriposi', 'Badasahi', 'Saraskana', 'Barsahi',
        ],
        'Punjab' => [
            'Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Mohali',
            'Hoshiarpur', 'Batala', 'Pathankot', 'Moga', 'Abohar', 'Malerkotla',
            'Phagwara', 'Barnala', 'Firozpur', 'Kapurthala', 'Sangrur', 'Ropar',
            'Nawanshahr', 'Tarn Taran', 'Gurdaspur', 'Fazilka', 'Faridkot',
            'Muktsar', 'Mansa', 'Kharar', 'Khanna', 'Samana', 'Nabha',
            'Rajpura', 'Dhuri', 'Sunam', 'Ahmedgarh', 'Gidderbaha',
            'Maler Kotla', 'Bhadson', 'Patiala', 'Nabha', 'Samana', 'Rajpura',
            'Bhadour', 'Bassi Pathana', 'Khamanon', 'Amloh', 'Fatehgarh Sahib',
            'Gobindgarh', 'Sirhind', 'Bassi', 'Amritsar', 'Ajnala', 'Majitha',
            'Raja Sansi', 'Rayya', 'Chaba', 'Tarn Taran', 'Bhubanian', 'Harike',
            'Patti', 'Khem Karan', 'Bhikhiwind', 'Naushera Panuan', 'Goindwal Sahib',
            'Batala', 'Sri Hargobindpur', 'Qadian', 'Dera Baba Nanak', 'Fatehgarh Churian',
            'Kalanaur', 'Kiri Afgana', 'Gurdaspur', 'Dinanagar', 'Kahnuwan',
            'Batala', 'Pathankot', 'Suchetgarh', 'Mamun', 'Narot Jaimal Singh',
            'Hoshiarpur', 'Dasua', 'Mukerian', 'Talwara', 'Garhshankar', 'Mahilpur',
            'Bhogpur', 'Adampur', 'Ladowali', 'Tanda', 'Kapurthala', 'Phagwara',
            'Sultanpur Lodhi', 'Bholath', 'Bhulath', 'Nadala', 'Nawanshahr',
            'Banga', 'Rahon', 'Balachaur', 'Sardulgarh', 'Muktsar', 'Malout',
            'Bariwala', 'Lambi', 'Gidderbaha', 'Faridkot', 'Kot Kapura',
            'Jaitu', 'Bathinda', 'Rampura Phul', 'Talwandi Sabo', 'Goniana',
            'Bhucho Mandi', 'Sangat', 'Maur', 'Raman', 'Mansa', 'Budhlada',
            'Sardulgarh', 'Baretta', 'Jalandhar', 'Nakodar', 'Phillaur', 'Kartarpur',
            'Nurmahal', 'Alawalpur', 'Bhagta', 'Adampur', 'Jalandhar Cantt',
            'Lohian', 'Goraya', 'Ludhiana', 'Khanna', 'Samrala', 'Sahnewal',
            'Doraha', 'Jagraon', 'Raikot', 'Mullanpur', 'Gill', 'Payal',
            'Machhiwara', 'Kohara', 'Khanpur', 'Firozpur', 'Zira', 'Guru Har Sahai',
            'Makhu', 'Talwandi Bhai', 'Firozpur Cantt', 'Sultanpur Lodhi',
            'Tarn Taran', 'Patti', 'Kasba', 'Shamchaurasi', 'Tarn Taran',
            'Sangrur', 'Barnala', 'Dhuri', 'Sunam', 'Malerkotla', 'Ahmedgarh',
            'Lehra', 'Bhana', 'Sangrur', 'Didba', 'Dirba', 'Sherpur',
            'Mohali', 'Kharar', 'Zirkpur', 'Banur', 'Lalru', 'Dera Bassi',
            'Kurali', 'Ropar', 'Anandpur Sahib', 'Nangal', 'Chamkaur Sahib',
            'Morinda', 'Rupnagar', 'Hoshiarpur', 'Bassi Pathana', 'Nurpur Bedi',
        ],
        'Rajasthan' => [
            'Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Bikaner', 'Ajmer', 'Bhilwara',
            'Alwar', 'Sikar', 'Bharatpur', 'Sri Ganganagar', 'Pali', 'Tonk',
            'Churu', 'Jhunjhunu', 'Hanumangarh', 'Kishangarh', 'Beawar', 'Dhaulpur',
            'Dungarpur', 'Sawai Madhopur', 'Banswara', 'Baran', 'Barmer', 'Bundi',
            'Chittorgarh', 'Churu', 'Dausa', 'Dholpur', 'Jaisalmer', 'Jalore',
            'Jhalawar', 'Karauli', 'Nagaur', 'Pratapgarh', 'Rajsamand', 'Sirohi',
            'Tonk', 'Sikar', 'Neem Ka Thana', 'Fatehpur', 'Lachhmangarh',
            'Khatoo', 'Reengus', 'Shrimadhopur', 'Sikar', 'Danta', 'Ramgarh',
            'Jaipur', 'Amer', 'Chaksu', 'Phulera', 'Jobner', 'Sanganer',
            'Shivdaspura', 'Kalwad', 'Kotputli', 'Viratnagar', 'Shahpura',
            'Mahuwa', 'Paota', 'Alwar', 'Bhiwadi', 'Khairthal', 'Tijara',
            'Behror', 'Mandawar', 'Ramgarh', 'Rajgarh', 'Kishangarh Bas',
            'Kathumar', 'Laxmangarh', 'Bansur', 'Thanagazi', 'Bharatpur',
            'Rupbas', 'Nadbai', 'Weir', 'Bayana', 'Bhusawar', 'Deeg',
            'Kaman', 'Nagar', 'Kumher', 'Karauli', 'Mandrail', 'Sapotra',
            'Todabhim', 'Hindaun', 'Dausa', 'Bandikui', 'Baswa', 'Lalsot',
            'Sikrai', 'Dholpur', 'Rajakhera', 'Bari', 'Dhaulpur',
            'Sawai Madhopur', 'Gangapur City', 'Khandar', 'Bamanwas', 'Bonli',
            'Chauth Ka Barwara', 'Malarna Dungar', 'Shahbad', 'Tonk', 'Deoli',
            'Malpura', 'Niwai', 'Todaraisingh', 'Kota', 'Ramganj Mandi',
            'Sangod', 'Suket', 'Bundi', 'Lakheri', 'Indragarh', 'Kaprain',
            'Barran', 'Antah', 'Atru', 'Chhabra', 'Chhipabarod', 'Kishanganj',
            'Aklera', 'Jhalawar', 'Patan', 'Raipur', 'Bhawanimandi', 'Pirawa',
            'Gangdhar', 'Akola', 'Bakani', 'Jodhpur', 'Bilara', 'Bhopalgarh',
            'Luni', 'Osian', 'Phalodi', 'Shergarh', 'Setrawa', 'Tivari',
            'Nagaur', 'Didwana', 'Jhunjhunu', 'Chirawa', 'Nawalgarh', 'Udaipurwati',
            'Mukandgarh', 'Pilani', 'Surajgarh', 'Khetri', 'Bissau', 'Buhana',
            'Kishangarh', 'Ajmer', 'Pushkar', 'Kekri', 'Sarwar', 'Masuda',
            'Beawar', 'Pisangan', 'Tantoti', 'Jawaja', 'Bhim', 'Deogarh',
            'Rajsamand', 'Kumbhalgarh', 'Rajsamand', 'Nathdwara', 'Kankroli',
            'Zawar', 'Amet', 'Bhilwara', 'Gangapur', 'Shahpura', 'Mandalgarh',
            'Sahara', 'Asind', 'Hurda', 'Kotri', 'Kotra', 'Pali', 'Bali',
            'Desuri', 'Marwar Junction', 'Raipur', 'Rani', 'Rohat', 'Sojat',
            'Sumerpur', 'Takhatgarh', 'Sirohi', 'Mount Abu', 'Abu Road',
            'Pindwara', 'Sheoganj', 'Sirohi', 'Reodar', 'Jalore', 'Bhinmal',
            'Sanchore', 'Ahore', 'Raniwara', 'Sayla', 'Bagoda', 'Bilara',
            'Jaisalmer', 'Pokhran', 'Sam', 'Ramgarh', 'Fatehgarh', 'Barmer',
            'Balotra', 'Pachpadra', 'Siwana', 'Gudamalani', 'Chohtan', 'Dhorimana',
            'Sindhari', 'Ramsar', 'Samdari', 'Baytu', 'Bikaner', 'Churu',
            'Sadulpur', 'Sardarshahar', 'Rajgarh', 'Taranagar', 'Sujangarh',
            'Ratangarh', 'Bidasar', 'Dungargarh', 'Nokha', 'Khajuwala',
            'Kolayat', 'Lunkaransar', 'Sri Ganganagar', 'Raisinghnagar',
            'Padampur', 'Karanpur', 'Kesrisinghpur', 'Suratgarh', 'Anupgarh',
            'Vijainagar', 'Gharshana', 'Rawatsar', 'Hanumangarh', 'Pilibanga',
            'Sangaria', 'Nohar', 'Bhadra', 'Tibbi', 'Gogamedi', 'Dabli Rathan',
            'Churu', 'Sujangarh', 'Ratangarh', 'Sardarshahar', 'Rajgarh',
            'Taranagar', 'Bidasar', 'Dungargarh', 'Nokha', 'Churu',
            'Udaipur', 'Gogunda', 'Jhadol', 'Kherwara', 'Kotra', 'Salumbar',
            'Sarada', 'Girwa', 'Mavli', 'Nathdwara', 'Rajsamand', 'Bhim',
            'Dungarpur', 'Sagwada', 'Aspur', 'Simalwara', 'Ghatol', 'Banswara',
            'Kushalgarh', 'Bagidora', 'Gharghoda', 'Partapur', 'Kushalgarh',
            'Banswara', 'Pratapgarh', 'Peepalkhoont', 'Chhoti Sadri',
            'Garhi', 'Bari Sadri', 'Arnod', 'Dholpur', 'Bari', 'Rajakhera',
        ],
        'Sikkim' => [
            'Gangtok', 'Namchi', 'Mangan', 'Gyalshing', 'Rhenock', 'Singtam',
            'Rangpo', 'Jorethang', 'Pakyong', 'Soreng', 'Ravangla', 'Pelling',
            'Yuksom', 'Lachen', 'Lachung', 'Chungthang', 'Mangan', 'Kabi',
            'Dikchu', 'Makha', 'Raley', 'Samdong', 'Tingda', 'Phadamchen',
            'Khamdong', 'Rankag', 'Turuk', 'Lingthem', 'Heegyang', 'Tashiding',
            'Legship', 'Geyzing', 'Gyalshing', 'Ravangla', 'Damthang',
            'Temi', 'Bermoik', 'Melli', 'Singtam', 'Rangpo', 'Changay',
            'Majitar', 'Rhenock', 'Rorathang', 'Panchghani', 'Lamagaon',
            'Pendam', 'Sajong', 'Pakyong', 'Nandok', 'Rateypani', 'Ranipool',
            'Rankag', 'Sangkhola', 'Sirwani', 'Barbing', 'Phong', 'Assangthang',
            'Nayabazar', 'Kaluk', 'Darap', 'Tashiding', 'Rinchenpong',
            'Soreng', 'Yuksom', 'Dentam', 'Hilley', 'Sangachoeling', 'Uttarey',
        ],
        'Tamil Nadu' => [
            'Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem',
            'Tirunelveli', 'Tiruppur', 'Erode', 'Vellore', 'Thoothukudi',
            'Dindigul', 'Thanjavur', 'Ranipet', 'Sivakasi', 'Karur',
            'Udhagamandalam', 'Hosur', 'Nagercoil', 'Kancheepuram', 'Kumbakonam',
            'Cuddalore', 'Rajapalayam', 'Pollachi', 'Tiruvannamalai', 'Tambaram',
            'Avadi', 'Chromepet', 'Pallavaram', 'Poonamallee', 'Ambattur',
            'Chengalpattu', 'Maraimalai Nagar', 'Tiruvallur', 'Arakkonam',
            'Kanchipuram', 'Sriperumbudur', 'Vandavasi', 'Uthiramerur', 'Madurantakam',
            'Cheyyar', 'Arni', 'Polur', 'Vellore', 'Gudiyatham', 'Tirupattur',
            'Ambur', 'Vaniyambadi', 'Pernambut', 'Krishnagiri', 'Bargur',
            'Denkanikottai', 'Hosur', 'Dharmapuri', 'Palacode', 'Pennagaram',
            'Harur', 'Pappireddipatti', 'Tiruvannamalai', 'Chengam', 'Arni',
            'Vandavasi', 'Polur', 'Chetpet', 'Gingee', 'Tirukovilur',
            'Sankarapuram', 'Kallakurichi', 'Ulundurpettai', 'Chinnasalem',
            'Salem', 'Attur', 'Omalur', 'Mettur', 'Edappadi', 'Sangagiri',
            'Yercaud', 'Namakkal', 'Tiruchengode', 'Rasipuram', 'Kumarapalayam',
            'Paramathi Velur', 'Erode', 'Bhavani', 'Gobichettipalayam', 'Sathyamangalam',
            'Perundurai', 'Dharapuram', 'Kangeyam', 'Tiruppur', 'Palladam',
            'Udamalpet', 'Avanashi', 'Coimbatore', 'Mettupalayam', 'Pollachi',
            'Valparai', 'Anaimalai', 'Kinathukadavu', 'The Nilgiris', 'Ooty',
            'Coonoor', 'Gudalur', 'Kotagiri', 'Dindigul', 'Kodaikanal',
            'Palani', 'Oddanchatram', 'Vedasandur', 'Natham', 'Nilakottai',
            'Karur', 'Kulithalai', 'Paramathi', 'Manapparai', 'Tiruchirappalli',
            'Musiri', 'Thottiyam', 'Lalgudi', 'Srirangam', 'Thuraiyur',
            'Perambalur', 'Chettipalayam', 'Ariyalur', 'Sendurai', 'Udayarpalayam',
            'Thanjavur', 'Kumbakonam', 'Pattukkottai', 'Thiruvaiyaru',
            'Papanasam', 'Orathanadu', 'Tiruvidaimarudur', 'Nagapattinam',
            'Mayiladuthurai', 'Sirkali', 'Vedaranyam', 'Tharangambadi',
            'Kuttalam', 'Tiruvarur', 'Mannargudi', 'Nannilam', 'Needamangalam',
            'Valangaiman', 'Kudavasal', 'Cuddalore', 'Chidambaram', 'Vriddhachalam',
            'Neyveli', 'Panruti', 'Tittagudi', 'Kattumannarkoil', 'Villupuram',
            'Tindivanam', 'Gingee', 'Vanur', 'Marakkanam', 'Vikravandi',
            'Kallakurichi', 'Ariyalur', 'Udayarpalayam', 'Ramanathapuram',
            'Paramakudi', 'Rameswaram', 'Kilakarai', 'Mudukulathur', 'Kadaladi',
            'Virudhunagar', 'Sivakasi', 'Rajapalayam', 'Sattur', 'Tenkasi',
            'Sivaganga', 'Manamadurai', 'Karaikudi', 'Tirupathur', 'Puducherry',
            'Tirunelveli', 'Palayamkottai', 'Tenkasi', 'Ambasamudram',
            'Sankarankovil', 'Nanguneri', 'Thoothukudi', 'Kovilpatti',
            'Kayalpattinam', 'Tiruvallur', 'Arakkonam', 'Tiruttani',
            'Pallipattu', 'Kanchipuram', 'Chengalpattu', 'Maduranthakam',
            'Cheyyur', 'Tambaram', 'Kancheepuram', 'Uthiramerur', 'Sriperumbudur',
            'Kanyakumari', 'Nagercoil', 'Killiyur', 'Thiruvattaru',
            'Kuzhithurai', 'Colachel', 'Padmanabhapuram',
        ],
        'Telangana' => [
            'Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Khammam',
            'Ramagundam', 'Mahbubnagar', 'Nalgonda', 'Adilabad', 'Suryapet',
            'Siddipet', 'Miryalaguda', 'Jagtial', 'Mancherial', 'Vikarabad',
            'Wanaparthy', 'Bhongir', 'Kothagudem', 'Bhadrachalam', 'Gadwal',
            'Jangaon', 'Kamareddy', 'Kagaznagar', 'Bellampalli', 'Mandi Marri',
            'Sirpur', 'Asifabad', 'Tandur', 'Zahirabad', 'Sadashivpet',
            'Sangareddy', 'Medak', 'Narsapur', 'Patancheru', 'Ramachandrapuram',
            'Bodhan', 'Armoor', 'Banchanapally', 'Korutla', 'Metpally',
            'Huzurabad', 'Jammikunta', 'Husnabad', 'Sultanabad', 'Peddapalli',
            'Polepally', 'Peddapally', 'Palakurthi', 'Devarakonda', 'Chandur',
            'Nakrekal', 'Kodad', 'Huzurnagar', 'Mellacheruvu', 'Bhongir',
            'Choutuppal', 'Ramannapeta', 'Valigonda', 'Bibinagar', 'Pochampally',
            'Nalgonda', 'Halimiyam', 'Kanagal', 'Madgulapally', 'Gurrampode',
            'Mahabubnagar', 'Jadcherla', 'Nawabpet', 'Shadnagar', 'Kothur',
            'Balanagar', 'Farooqnagar', 'Amangal', 'Kesamudram', 'Mahabubabad',
            'Maripeda', 'Dornakal', 'Kothagudem', 'Palwancha', 'Yellandu',
            'Gollapalli', 'Ashwaraopet', 'Burgampadu', 'Mulkalapally', 'Penchikalapadu',
            'Khammam', 'Sathupalli', 'Kallur', 'Bonakal', 'Tirumalayapalem',
            'Wyra', 'Warangal', 'Hanamkonda', 'Kazipet', 'Ghanpur Station',
            'Shayampet', 'Palakurthi', 'Thorur', 'Ghanpur', 'Narsampet',
            'Parkal', 'Atmakur', 'Jangaon', 'Ghanpur', 'Bachannapet',
            'Devaruppala', 'Kodkal', 'Vikarabad', 'Pargi', 'Tandur', 'Basheerabad',
            'Kodangal', 'Doma', 'Marpally', 'Nawabpet', 'Shamshabad',
            'Rajendranagar', 'Ibrahimpatnam', 'Moinabad', 'Hayathnagar',
            'Chevella', 'Shankarpally', 'Shadnagar', 'Adilabad', 'Utnur',
            'Bhainsa', 'Mudhole', 'Lokeswaram', 'Boath', 'Nirmal',
            'Basar', 'Khanapur', 'Nizamabad', 'Morthad', 'Yellareddy',
            'Banswada', 'Kamareddy', 'Bichkunda', 'Pitlam', 'Dudgaon',
            'Sadasivanagar', 'Bhiknoor', 'Jukkal', 'Madnur', 'Nandipet',
            'Sirsilla', 'Vemulawada', 'Sircilla', 'Kamanpur', 'Chandurti',
            'Gambhiraopet', 'Karimnagar', 'Huzurabad', 'Jammikunta', 'Ramagundam',
            'Peddapalle', 'Manthani', 'Ramagiri', 'Ragunathpally', 'Kamanpur',
            'Husnabad', 'Sultanabad', 'Elgaid', 'Kamalapur', 'Karimnagar',
            'Choppadandi', 'Medipally', 'Gangadhara', 'Yellareddipet', 'Sangareddy',
            'Patancheru', 'Zaheerabad', 'Sadashivpet', 'Narayankhed', 'Jharasangham',
            'Sadasivpet', 'Kondapur', 'Kohir', 'Nyalata', 'Ramchandrapuram',
            'Medak', 'Siddipet', 'Dubbak', 'Narsapur', 'Gajwel', 'Tekmal',
            'Shankarampet', 'Pappannapet', 'Ramayampet', 'Yeldurthy', 'Mulug',
            'Narayanapur', 'Hyderabad Central', 'Secunderabad',
        ],
        'Tripura' => [
            'Agartala', 'Udaipur', 'Dharmanagar', 'Kailasahar', 'Ambassa',
            'Belonia', 'Khowai', 'Teliamura', 'Sabroom', 'Sonamura',
            'Bishalgarh', 'Ranirbazar', 'Melaghar', 'Kamalpur', 'Kumarghat',
            'Khowai', 'Mohanpur', 'Jirania', 'Pratapgarh', 'Bishramganj',
            'Hezamara', 'Mandwi', 'Panisagar', 'Dharam Nagar', 'Kadamtala',
            'Dasda', 'Jampuijala', 'Sekerkote', 'Bardowali', 'Gakulnagar',
            'Bishramganj', 'Mohanpur', 'Mungiakami', 'Padmabil', 'Surjamaninagar',
            'Briddhanagar', 'Majlishpur', 'Khowai', 'Kalyanpur', 'Krishnapur',
            'Ramachandraghat', 'Sakurabazar', 'Amarpur', 'Nalicherra', 'Salgarah',
            'Sonamura', 'Bagber', 'Kakraban', 'Kamalpur', 'Barmabaria',
            'Raima', 'Satchand', 'Manu Valley', 'Kila', 'Ganganagar',
            'Dangapara', 'Fatikroy', 'Kurti', 'Jubarajnagar', 'North Krishnapur',
            'Bishalgarh', 'Charilam', 'Jirania', 'Mohanpur', 'Ranirbazar',
            'Khowai', 'Kalyanpur', 'Teliamura', 'Mohalchari', 'Khowai',
            'Udaipur', 'Bokafa', 'Gournagar', 'Kakraban', 'Rajnagar',
            'Satchand', 'Silachari', 'Tepania', 'Amarpur', 'Barmabaria',
            'Bagafa', 'Belonia', 'Hrishyamukh', 'Sukhamani', 'Manubazar',
            'Rajapur', 'Srinagar', 'Chandrapur', 'Sangram', 'Santirbazar',
            'Manik Bhander', 'Pulinpur', 'Bakim', 'Bilthai', 'Birendranagar',
            'Killa', 'Kakulya', 'Bhadr', 'Fatikroy', 'Haludiban',
            'Ambassa', 'Ganganagar', 'Durgachowmuhani', 'Dalubari', 'Mungiakumi',
            'Pecharathal', 'Burabari', 'Halflong', 'Jarulboni', 'Longai',
            'Longachara', 'Mohanpur', 'Naganjit', 'Narayanbari', 'Satchand',
            'Sonatala', 'Tilthai', 'Uptakhali', 'Versha',
        ],
        'Uttar Pradesh' => [
            'Lucknow', 'Kanpur', 'Agra', 'Varanasi', 'Meerut', 'Prayagraj',
            'Ghaziabad', 'Noida', 'Bareilly', 'Aligarh', 'Moradabad', 'Gorakhpur',
            'Saharanpur', 'Jhansi', 'Firozabad', 'Mathura', 'Muzaffarnagar',
            'Shahjahanpur', 'Rampur', 'Ayodhya', 'Sultanpur', 'Etawah', 'Loni',
            'Hapur', 'Amroha', 'Bulandshahr', 'Bahraich', 'Azamgarh', 'Unnao',
            'Rae Bareli', 'Sitapur', 'Hardoi', 'Lakhimpur Kheri', 'Basti',
            'Banda', 'Etah', 'Mainpuri', 'Mau', 'Ballia', 'Gonda',
            'Chitrakoot', 'Deoria', 'Ghazipur', 'Hamirpur', 'Jalaun',
            'Kannauj', 'Kaushambi', 'Kushinagar', 'Lalitpur', 'Mahoba',
            'Maharajganj', 'Mahamaya Nagar', 'Mirzapur', 'Mohanlalganj',
            'Pratapgarh', 'Sant Kabir Nagar', 'Sant Ravidas Nagar', 'Shamli',
            'Shrawasti', 'Siddharthnagar', 'Sonbhadra', 'Amethi', 'Mirzapur',
            'Saharanpur', 'Deoband', 'Nakur', 'Gangoh', 'Sarsawa', 'Behat',
            'Muzaffarnagar', 'Shamli', 'Kairana', 'Budhana', 'Jansath',
            'Khatauli', 'Bagpat', 'Baraut', 'Baghpat', 'Meerut', 'Mawana',
            'Sardhana', 'Ghaziabad', 'Modinagar', 'Dasna', 'Hapur',
            'Pilkhuwa', 'Bulandshahr', 'Sikandarabad', 'Khurja', 'Dibai',
            'Siyana', 'Jahangirabad', 'Anupshahr', 'Debai', 'Shikarpur',
            'Aligarh', 'Atrauli', 'Khair', 'Iglas', 'Koil', 'Sasni',
            'Hathras', 'Sasni', 'Mursan', 'Sikandra Rao', 'Mahamaya Nagar',
            'Agrawal', 'Etah', 'Jalesar', 'Kasganj', 'Patiyali', 'Soron',
            'Mainpuri', 'Bhogaon', 'Kishni', 'Kuraoli', 'Ghirauli',
            'Firozabad', 'Shikohabad', 'Tundla', 'Jasrana', 'Fatehabad',
            'Mathura', 'Vrindavan', 'Chhata', 'Govardhan', 'Mant', 'Baldeo',
            'Agra', 'Fatehpur Sikri', 'Kiraoli', 'Kheragarh', 'Shamsabad',
            'Bah', 'Achnera', 'Jagner', 'Dhaulpur', 'Morena', 'Bhander',
            'Kanpur', 'Kanpur Cantonment', 'Bilhaur', 'Ghatampur', 'Narwal',
            'Akbarpur', 'Sachendi', 'Fatehpur', 'Banda', 'Atarra', 'Naraini',
            'Baberi', 'Pailani', 'Mahoba', 'Charkhari', 'Kulpahar', 'Hamirpur',
            'Rath', 'Maudaha', 'Jalaun', 'Orai', 'Kalpi', 'Konch',
            'Madhogarh', 'Jhansi', 'Garautha', 'Mauranipur', 'Moth',
            'Lalitpur', 'Talbehat', 'Mahroni', 'Lucknow', 'Malihabad',
            'Bakshi Ka Talab', 'Mohanlalganj', 'Gosainganj', 'Kakori',
            'Nagram', 'Unnao', 'Bangarmau', 'Safipur', 'Hasanganj',
            'Mohan', 'Purwa', 'Bighapur', 'Rae Bareli', 'Dalmau', 'Bachhrawan',
            'Mahrajganj', 'Salon', 'Unchahar', 'Jais', 'Amethi', 'Musafirkhana',
            'Gauriganj', 'Tiloi', 'Sultanpur', 'Lambhua', 'Kadipur',
            'Goshainganj', 'Hardoi', 'Sawaiyajpur', 'Sandila', 'Bilgram',
            'Shahabad', 'Pihani', 'Gopamau', 'Kachhauna', 'Sandi',
            'Sitapur', 'Biswan', 'Sidhauli', 'Misrikh', 'Laharpur',
            'Mahmudabad', 'Khairtabad', 'Gondamau', 'Lakhimpur Kheri',
            'Mohammdi', 'Gola Gokarannath', 'Palia', 'Nighasan', 'Mitauli',
            'Pasgawan', 'Bankeyganj', 'Bahraich', 'Nanpara', 'Risia', 'Kaiserganj',
            'Mahasi', 'Jarwal', 'Fakharpur', 'Katra', 'Shrawasti', 'Ikauna',
            'Bhinga', 'Bhanpur', 'Gonda', 'Balrampur', 'Utraula', 'Tulsipur',
            'Gainsari', 'Tarabganj', 'Nawabganj', 'Colonelganj', 'Barabanki',
            'Fatehpur', 'Haidergarh', 'Ramsanehighat', 'Safdarganj', 'Sirauli',
            'Ayodhya', 'Bikapur', 'Rudauli', 'Milkipur', 'Sohawal',
            'Goshainganj', 'Ambedkarnagar', 'Akbarpur', 'Jalalpur', 'Tanda',
            'Allapur', 'Basti', 'Harraiya', 'Bhanpur', 'Rudhauli',
            'Domariyaganj', 'Khalilabad', 'Bansi', 'Ghanghata', 'Chauri Chaura',
            'Sant Kabir Nagar', 'Mehdawal', 'Naugarh', 'Barhani', 'Bansi',
            'Siddharthnagar', 'Shohratgarh', 'Bargadwa', 'Bhanpur', 'Mahadeva',
            'Gorakhpur', 'Sahajanwa', 'Kauriram', 'Pipraich', 'Gola',
            'Barhalganj', 'Khajani', 'Chauri Chaura', 'Campierganj', 'Deoria',
            'Bhatpar Rani', 'Salempur', 'Barhaj', 'Lar', 'Bhagalpur',
            'Gaura', 'Mau', 'Madhuban', 'Ghosi', 'Maunath Bhanjan',
            'Muhammadabad Gohna', 'Ballia', 'Rasra', 'Bansdih', 'Belthara Road',
            'Siarh', 'Reoti', 'Sikanderpur', 'Shahganj', 'Azamgarh',
            'Phulpur', 'Nigohi', 'Sagri', 'Lalganj', 'Maharajganj', 'Nizamabad',
            'Mubarakpur', 'Palhani', 'Jaunpur', 'Machhlishahr', 'Mariyahu',
            'Shahganj', 'Badlapur', 'Kerakat', 'Ghazipur', 'Zamania',
            'Yusufpur', 'Saidpur', 'Bahadurganj', 'Mahmudabad', 'Seorai',
            'Mughalsarai', 'Chandauli', 'Sakaldiha', 'Chakia', 'Naugarh',
            'Mirzapur', 'Chunar', 'Madihan', 'Ghorawal', 'Lalganj',
            'Sonbhadra', 'Robertsganj', 'Dudhi', 'Pipri', 'Kone',
            'Varanasi', 'Pindra', 'Sevapuri', 'Gangapur', 'Kashi Vidyapeeth',
            'Cholapur', 'Harhua', 'Baraut', 'Phulpur', 'Handia', 'Soraon',
            'Pratapgarh', 'Kunda', 'Patti', 'Lalganj', 'Kanpur Dehat',
            'Akbarpur', 'Bhognipur', 'Jhinjhak', 'Rannipur', 'Rasulabad',
        ],
        'Uttarakhand' => [
            'Dehradun', 'Haridwar', 'Rishikesh', 'Roorkee', 'Haldwani', 'Rudrapur',
            'Kashipur', 'Nainital', 'Mussoorie', 'Almora', 'Pithoragarh',
            'Kotdwar', 'Ramnagar', 'Sitarganj', 'Manglaur', 'Bageshwar',
            'Champawat', 'Khatima', 'Jaspur', 'Bazpur', 'Gadarpur', 'Kichha',
            'Sitarganj', 'Rudrapur', 'Piran Kaliyar', 'Laksar', 'Jhabrera',
            'Roorkee', 'Kankhal', 'Bhadrabad', 'Chandpur', 'Manglaur',
            'Landour', 'Dhanaulti', 'Sahastradhara', 'Dehradun', 'Vikasnagar',
            'Herbertpur', 'Kalsi', 'Rishikesh', 'Shyampur', 'Doiwala',
            'Malsi', 'Dehradun Cantt', 'Clement Town', 'Premnagar', 'Raipur',
            'Mussoorie', 'Lakshmipur', 'Kempty', 'Kimadi', 'Sangla',
            'Nainital', 'Bhowali', 'Ramnagar', 'Kaladhungi', 'Bhimtal',
            'Sattal', 'Naukuchiatal', 'Mukteshwar', 'Haldwani', 'Lalkuan',
            'Kathgodam', 'Rudrapur', 'Pantnagar', 'Almora', 'Ranikhet',
            'Dwarahat', 'Chaukhutiya', 'Someshwar', 'Dhanachuli', 'Bageshwar',
            'Kapkot', 'Kanda', 'Garur', 'Jalna', 'Baijnath', 'Kausani',
            'Chamoli', 'Gopeshwar', 'Joshimath', 'Badrinath', 'Karnaprayag',
            'Nandaprayag', 'Pipalkoti', 'Chandrashila', 'Rudraprayag',
            'Kedarnath', 'Kund', 'Guptkashi', 'Phata', 'Tilwara',
            'Pauri', 'Kotdwar', 'Lansdowne', 'Srinagar', 'Khirsu',
            'Dugadda', 'Satpuli', 'Thalisain', 'Dogadda', 'Kotdwara',
            'Pithoragarh', 'Dharchula', 'Didihat', 'Berinag', 'Gangolihat',
            'Munsyari', 'Champawat', 'Tanakpur', 'Banbasa', 'Lohaghat',
            'Purnagiri', 'Jauljibi', 'Nepalgunj', 'Champawat Town',
            'Uttarkashi', 'Gangotri', 'Yamunotri', 'Barkot', 'Purola',
            'Mori', 'Rajat', 'Dunda', 'Chinyalisaur', 'Harsil',
            'Tehri Garhwal', 'New Tehri', 'Devprayag', 'Kirtinagar', 'Muni Ki Reti',
            'Ghansali', 'Narender Nagar', 'Chamba', 'Dhanaulti', 'Kiroli',
            'Dharasu', 'Kakuwala', 'Tapovan', 'Laxman Jhoola', 'Ram Jhoola',
        ],
        'West Bengal' => [
            'Kolkata', 'Howrah', 'Durgapur', 'Asansol', 'Siliguri', 'Bardhaman',
            'Krishnanagar', 'Malda', 'Baharampur', 'Habra', 'Ranaghat', 'Jalpaiguri',
            'Darjeeling', 'Cooch Behar', 'Haldia', 'Balurghat', 'Raiganj',
            'Medinipur', 'Bangaon', 'English Bazar', 'Contai', 'Rampurhat',
            'Basirhat', 'Diamond Harbour', 'Nabadwip', 'Uluberia', 'Serampore',
            'Chandannagar', 'Bhadreswar', 'Champdani', 'Baidyabati', 'Rishra',
            'Konnagar', 'Dankuni', 'Masat', 'Bally', 'Barrackpore', 'Barasat',
            'Madhyamgram', 'Dum Dum', 'South Dum Dum', 'North Dum Dum', 'Kamarhati',
            'Panihati', 'Khardaha', 'Titagarh', 'Baranagar', 'Belgharia',
            'Agarpara', 'Sodepur', 'Bhatpara', 'Naihati', 'Halisahar',
            'Kanchrapara', 'Kalyani', 'Gayespur', 'Shantipur', 'Phulia',
            'Basirhat', 'Taki', 'Baduria', 'Gobardanga', 'Ashoknagar Kalyangarh',
            'Rajarhat Gopalpur', 'New Barrackpore', 'Bidhannagar', 'Salt Lake',
            'Sonarpur', 'Rajpur Sonarpur', 'Baruipur', 'Jaynagar Majilpur',
            'Canning', 'Budge Budge', 'Maheshtala', 'Pujali', 'Bawali',
            'Chakdaha', 'Kalyani', 'Memari', 'Katwa', 'Kalna', 'Guskara',
            'Manteswar', 'Raina', 'Khandaghosh', 'Bhatar', 'Jamalpur',
            'Purbasthali', 'Sainthia', 'Suri', 'Bolpur', 'Rampurhat',
            'Tarapith', 'Dubrajpur', 'Siuri', 'Illambazar', 'Nalhati',
            'Murarai', 'Raghunathpur', 'Chittaranjan', 'Bhojudih', 'Kulti',
            'Barakar', 'Raniganj', 'Jamuria', 'Sitarampur', 'Neamatpur',
            'Burnpur', 'Ukhra', 'Pandaveswar', 'Parasia', 'Jhanjra',
            'Amlajora', 'Sonamukhi', 'Bishnupur', 'Bankura', 'Khatra',
            'Patrasayer', 'Indas', 'Simlapal', 'Ranibandh', 'Hirbandh',
            'Barjora', 'Gangajalghati', 'Mejia', 'Jhantipahari', 'Taldangra',
            'Joypur', 'Saltora', 'Chhatna', 'Raipur', 'Sarenga', 'Garbeta',
            'Chandrakona', 'Kharagpur', 'Midnapore', 'Jhargram', 'Gopiballavpur',
            'Nayagram', 'Keshiary', 'Dantan', 'Mohana', 'Egra', 'Bhagabanpur',
            'Patashpur', 'Ramnagar', 'Khejuri', 'Chandipur', 'Tamluk',
            'Panskura', 'Haldia', 'Mahishadal', 'Sutahata', 'Nandigram',
            'Moyna', 'Kolaghat', 'Arambag', 'Tarakeswar', 'Jangipur',
            'Jiaganj', 'Lalgola', 'Samsherganj', 'Nurpur', 'Raghunathganj',
            'Farakka', 'Samserganj', 'Suti', 'Sagardighi', 'Ratua',
            'Manikchak', 'Chanchal', 'Harischandrapur', 'Gazole', 'Bamangola',
            'Habibpur', 'Bamongola', 'Bulbulchandi', 'Mothabari', 'Kaliachak',
            'Old Malda', 'Kumarganj', 'Tapan', 'Gangarampur', 'Harirampur',
            'Dhupguri', 'Mainaguri', 'Malbazar', 'Alipurduar', 'Falakata',
            'Kalchini', 'Madarihat', 'Kumargram', 'Nagrakata', 'Matiali',
            'Maynaguri', 'Rajganj', 'Islampur', 'Goalpokhar', 'Chopra',
            'Karandighi', 'Dalkhola', 'Kaliaganj', 'Hemtabad', 'Itahar',
            'Kushmundi', 'Bansihari', 'Tapan', 'Balurghat', 'Kumarganj',
            'Hilli', 'Gangarampur', 'Harirampur', 'Kushmandi', 'Banshihari',
            'Tufanganj', 'Mathabhanga', 'Mekliganj', 'Sitalkuchi', 'Haldibari',
            'Dinhata', 'Koch Bihar', 'Murshidabad', 'Kandi', 'Beldanga',
            'Domkal', 'Bhagawangola', 'Hariharpara', 'Nawda', 'Raninagar',
            'Jalangi', 'Debagram', 'Nakashipara', 'Chapra', 'Tehatta',
            'Dhaniakhali', 'Gurap', 'Sheakhala', 'Pursurah', 'Khanakul',
            'Balagarh', 'Pandua', 'Singur', 'Goghat', 'Chanditala',
            'Jangipara', 'Haripal', 'Tarakeswar', 'Kashinagar',
            'Maynaguri', 'Falakata', 'Alipurduar', 'Kalchini', 'Kumargram',
            'Sitai', 'Sitalkuchi', 'Haldibari', 'Mekliganj', 'Mathabhanga',
            'Dinhata', 'Koch Bihar', 'Saldaha', 'Kharibari', 'Phansidewa',
            'Naxalbari', 'Matigara', 'Kurseong', 'Mirik', 'Sukna',
            'Mahanadi', 'Batasi', 'Lodhoma', 'Jorebunglow', 'Rangli Rangliot',
            'Tonglu', 'Tumlong', 'Singalila', 'Rimbik', 'Lava',
            'Lolegaon', 'Takda', 'Rishyap', 'Rishop', 'Sittong',
        ],
        'Andaman and Nicobar Islands' => [
            'Port Blair', 'Bambooflat', 'Diglipur', 'Rangat', 'Mayabunder',
            'Hut Bay', 'Car Nicobar', 'Campbell Bay', 'Wandoor', 'Neil Island',
            'Havelock', 'Swaraj Dweep', 'Shaheed Dweep', 'Long Island',
            'Strait Island', 'Little Andaman', 'Baratang', 'Middle Andaman',
            'North Andaman', 'South Andaman', 'Chidiya Tapu', 'Ross Island',
            'Viper Island', 'North Bay', 'Elephant Beach', 'Laxmanpur',
            'Radhanagar', 'Kala Pahar', 'Jolly Buoy', 'Cinque Island',
            'Tarmugli', 'Rutland', 'Sitapur', 'Karmatang', 'Noe Kera',
            'Namo', 'Kadamtala', 'Bakultala', 'Rampur', 'Gandhighat',
            'Kalipur', 'Durgapur', 'Gandhi Nagar', 'Mithakhari',
            'Bimbitan', 'Gobind Nagar', 'Bibipur', 'Urmilapur', 'Swadesh',
        ],
        'Chandigarh' => [
            'Chandigarh', 'Sector 1', 'Sector 2', 'Sector 3', 'Sector 4',
            'Sector 5', 'Sector 6', 'Sector 7', 'Sector 8', 'Sector 9',
            'Sector 10', 'Sector 11', 'Sector 12', 'Sector 13', 'Sector 14',
            'Sector 15', 'Sector 16', 'Sector 17', 'Sector 18', 'Sector 19',
            'Sector 20', 'Sector 21', 'Sector 22', 'Sector 23', 'Sector 24',
            'Sector 25', 'Sector 26', 'Sector 27', 'Sector 28', 'Sector 29',
            'Sector 30', 'Sector 31', 'Sector 32', 'Sector 33', 'Sector 34',
            'Sector 35', 'Sector 36', 'Sector 37', 'Sector 38', 'Sector 39',
            'Sector 40', 'Sector 41', 'Sector 42', 'Sector 43', 'Sector 44',
            'Sector 45', 'Sector 46', 'Sector 47', 'Sector 48', 'Sector 49',
            'Sector 50', 'Sector 51', 'Sector 52', 'Sector 53', 'Sector 54',
            'Sector 55', 'Sector 56', 'Sector 57', 'Sector 58', 'Sector 59',
            'Sector 60', 'Sector 61', 'Sector 62', 'Manimajra', 'Daria',
            'Kajheri', 'Hallomajra', 'Kaimbwala', 'Khuda Jassu',
            'Khuda Ali Sher', 'Khuda Lahora', 'Chandigarh City',
            'Chandigarh Capital Region',
        ],
        'Dadra and Nagar Haveli and Daman and Diu' => [
            'Silvassa', 'Daman', 'Diu', 'Amli', 'Naroli', 'Rakholi',
            'Samarvarni', 'Masat', 'Khadoli', 'Dabhel', 'Vasona', 'Indreshwar',
            'Masat', 'Sarod', 'Velugam', 'Khanvel', 'Chandrapada', 'Vanakbara',
            'Bamonsa', 'Bhanvad', 'Bhitargarh', 'Bodal', 'Charchit',
            'Chikhli', 'Dharampur', 'Dhavad', 'Dudhani', 'Ghadavi',
            'Hedvi', 'Karchond', 'Khadki', 'Kotar', 'Kunjvada',
            'Mithi', 'Mogarpada', 'Mor', 'Nana Razithai', 'Naroli',
            'Palsana', 'Paradi', 'Patlai', 'Pimpardi', 'Piplad',
            'Punadevi', 'Ranveri', 'Sarona', 'Sili', 'Sindh Bhat',
            'Somni', 'Thembha', 'Udvada', 'Umarkui', 'Valkani',
            'Vasona', 'Vasna', 'Zari', 'Amad', 'Bhurasi',
            'Chinchondi', 'Dabsi', 'Daman', 'Devka', 'Jampor',
            'Kachigam', 'Kadhaiya', 'Marwad', 'Nani Daman', 'Varkund',
        ],
        'Delhi' => [
            'New Delhi', 'Delhi', 'Dwarka', 'Rohini', 'Saket', 'Karol Bagh',
            'Connaught Place', 'Lajpat Nagar', 'Hauz Khas', 'Vasant Kunj',
            'Pitampura', 'Janakpuri', 'Preet Vihar', 'Patparganj', 'Nehru Place',
            'Okhla', 'Mehrauli', 'Chanakyapuri', 'Rajouri Garden', 'Kashmere Gate',
            'Chandni Chowk', 'Daryaganj', 'Paharganj', 'Sadar Bazar',
            'Shahdara', 'Seelampur', 'Shastri Park', 'Geeta Colony',
            'Kashmiri Gate', 'Laxmi Nagar', 'Karkardooma', 'Moti Nagar',
            'Punjabi Bagh', 'Paschim Vihar', 'Nangloi', 'Uttam Nagar',
            'Vikaspuri', 'Jangpura', 'Bhogal', 'Jamia Nagar', 'Sangam Vihar',
            'Sarita Vihar', 'Badarpur', 'Tughlakabad', 'Govindpuri',
            'Kalkaji', 'Alaknanda', 'Greater Kailash', 'Kailash Colony',
            'East of Kailash', 'Chittaranjan Park', 'Shivaji Nagar',
            'Kamla Nagar', 'Civil Lines', 'Sadar Bazar', 'Paharganj',
            'Model Town', 'Azadpur', 'Ashok Vihar', 'Wazirpur',
            'Shalimar Bagh', 'Harsh Vihar', 'Jahangirpuri', 'Samaypur Badli',
            'Burari', 'Sant Nagar', 'Timarpur', 'Nirankari Colony',
            'Mukherjee Nagar', 'Dhaka', 'Kashmir House', 'Raja Garden',
            'Tilak Nagar', 'Subhash Nagar', 'Tagore Garden', 'Kirti Nagar',
            'Naraina Vihar', 'Indrapuri', 'Shakur Basti', 'Sarojini Nagar',
            'Kidwai Nagar', 'Moti Bagh', 'R K Puram', 'Malviya Nagar',
            'Gulmohar Park', 'Safdarjung Enclave', 'Green Park', 'JNU',
            'Vasant Vihar', 'Munirka', 'R K Puram', 'Brar Square',
            'Delhi Cantt', 'Palam', 'Mahipalpur', 'Vasant Gaon',
            'Bijwasan', 'Najafgarh', 'Dwarka Sector', 'Dichaon Kalan',
            'Baprola', 'Nangal Raya', 'Kanjhawla', 'Mundka', 'Nangloi Jat',
            'Tikri Kalan', 'Rani Khera', 'Karala', 'Bawana', 'Alipur',
            'Holambi Kalan', 'Singhu', 'Narela', 'Bankner', 'Bhorgarh',
            'Inder Enclave', 'Mangolpuri', 'Sultanpuri', 'Madipur',
            'Paschim Vihar', 'Shiv Vihar', 'Sunder Nagari', 'Maujpur',
            'Babarpur', 'Jafrabad', 'Mustafabad', 'Zafrabad', 'Welcome Colony',
            'Gokalpuri', 'Jhilmil', 'Dilshad Garden', 'Anand Vihar',
            'Vishwas Nagar', 'Mandawali', 'New Usmanpur', 'Gautampuri',
            'Pandav Nagar', 'Surajmal Vihar', 'Mayur Vihar', 'Vasundhara Enclave',
            'Trilokpuri', 'Kalyanpuri', 'Madhu Vihar', 'Kondli', 'Dallupura',
            'Chilla', 'Gharoli', 'New Kondli', 'Hargovind Enclave',
            'Bharat Nagar', 'Yamuna Vihar', 'Bhajanpura', 'Usmanpur',
        ],
        'Jammu and Kashmir' => [
            'Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Sopore', 'Kathua',
            'Udhampur', 'Pulwama', 'Kupwara', 'Rajouri', 'Poonch', 'Bandipora',
            'Ganderbal', 'Kulgam', 'Budgam', 'Samba', 'Reasi', 'Doda',
            'Kishtwar', 'Ramban', 'Handwara', 'Kulgam', 'Shopian', 'Akhnoor',
            'Bari Brahmana', 'Basholi', 'Bhadarwah', 'Bijbehara', 'Charar-i-Sharief',
            'Doru Shahabad', 'Gool', 'Gulabgarh', 'Jourian', 'Katra', 'Khour',
            'Kishtwar', 'Lar', 'Magam', 'Mahore', 'Mattan', 'Nowshera',
            'Pampore', 'Pattan', 'Qazigund', 'Ramban', 'Ramgarh', 'Riasi',
            'Sumbal', 'Tangmarg', 'Tral', 'Uri', 'Vijaypur', 'Wagoora',
            'Kralpora', 'Kunzer', 'Kupwara', 'Langate', 'Lolab', 'Mawar',
            'Sogam', 'Trehgam', 'Zainapora', 'Anantnag', 'Dooru', 'Kokernag',
            'Larnoo', 'Pahalgam', 'Shangus', 'Verinag', 'Achabal', 'Bata Pora',
            'Gunder', 'Kulgam', 'Qaimoh', 'Rohama', 'Tangmarg', 'Wahabpora',
            'Bandipora', 'Gund Jehangir', 'Hajin', 'Kargam', 'Narwaw',
            'Sonawari', 'Ganderbal', 'Kangan', 'Mansbal', 'Nunar',
            'Wakura', 'Budgam', 'Beerwah', 'Khag', 'Khansahib', 'Charari',
            'Chadoora', 'Budgam', 'Nagam', 'Peth', 'Tujan', 'Asham',
            'Jammu', 'Bishnah', 'Bhalwal', 'Dinga Amb', 'Gangyal', 'Jammu Cantt',
            'Marh', 'Miran Sahib', 'Nagada', 'Purmandal', 'Ramgarh',
            'Raya', 'Samba', 'Satyari', 'Vijaypur', 'Akhnoor', 'Jourian',
            'Kharah', 'Maira Mandrian', 'Nud', 'Palanoorkalan', 'Pargwal',
            'Reasi', 'Bhabore', 'Ghordi', 'Gulabgarh', 'Jij', 'Katra',
            'Mahore', 'Pouni', 'Reasi', 'Sansari', 'Talwara', 'Tote',
            'Udhampur', 'Basohli', 'Billawar', 'Bani', 'Cherari', 'Dudu',
            'Ghordi', 'Kanthi', 'Mahanpur', 'Mendhar', 'Panjgrain',
            'Ramnagar', 'Shooni', 'Sukrala', 'Tikri', 'Bhadarwah', 'Bhalessa',
            'Bhaderwah', 'Chingam', 'Doda', 'Gandoh', 'Goha', 'Jodhpur',
            'Kahara', 'Kastigarh', 'Marmat', 'Premnagar', 'Pul Doda',
            'Ramban', 'Batote', 'Gool', 'Gughal', 'Mastagore', 'Pogal',
            'Rajouri', 'Beri', 'Budhal', 'Darhal', 'Dhammi', 'Kalar',
            'Kandi', 'Kotranka', 'Manjakote', 'Nowshera', 'Pouni', 'Rajouri',
            'Seela', 'Siot', 'Sunderbani', 'Thanamandi', 'Poonch', 'Abbasabad',
            'Balakote', 'Bandi', 'Chandak', 'Gursai', 'Haveli', 'Harni',
            'Mandi', 'Mankote', 'Mendhar', 'Poonch', 'Sawjian', 'Surankote',
            'Hiranagar', 'Kathua', 'Bani', 'Bhadu', 'Billawar', 'Chak',
            'Dingambra', 'Jandi', 'Keerian', 'Kharote', 'Ladwa', 'Mahanpur',
            'Marheen', 'Nathadda', 'Nandwal', 'Parole', 'Rajpura', 'Safapur',
            'Saidpur', 'Sajwal', 'Samba', 'Sangrampur', 'Sujanshah', 'Tajwal',
        ],
        'Ladakh' => [
            'Leh', 'Kargil', 'Nubra', 'Zanskar', 'Diskit', 'Hunder', 'Khalatse',
            'Nyoma', 'Padum', 'Drass', 'Shyok', 'Turtuk', 'Thoise', 'Durbuk',
            'Sankoo', 'Trespone', 'Mulbekh', 'Pashkum', 'Chiktan', 'Khalsi',
            'Hanu', 'Dha', 'Biama', 'Nurla', 'Basgo', 'Saspol', 'Alchi',
            'Nimoo', 'Upshi', 'Chumathang', 'Nubra Valley', 'Sumur', 'Sakti',
            'Hemis', 'Thiksey', 'Chemrey', 'Phyang', 'Karu', 'Shey',
            'Tikse', 'Khardong La', 'Chang La', 'Tanglang La', 'Fatu La',
            'Kargil Town', 'Wakha', 'Rangdum', 'Panikhar', 'Stakna',
            'Matho', 'Stok', 'Chushul', 'Hanle', 'Tangste', 'Demchok',
            'Koyul', 'Daulat Beg Oldie', 'Siachen Base Camp', 'Partapur',
            'Chalunka', 'Tyaq', 'Thang', 'Batalik', 'Kharbu', 'Shilong',
            'Lungnak', 'Dorzong', 'Mangyu', 'Doda', 'Aryan Valley',
            'Himya', 'Batal', 'Sarchu', 'More Plains', 'Debring',
            'Tsomoriri', 'Tsokar', 'Puga Valley', 'Chumur',
        ],
        'Lakshadweep' => [
            'Kavaratti', 'Agatti', 'Andrott', 'Amini', 'Kadmat', 'Kalpeni',
            'Minicoy', 'Bangaram', 'Bitra', 'Chetlat', 'Kiltan', 'Kadmat',
            'Suheli Par', 'Valiyakara', 'Cheriyakara', 'Thinakara',
            'Pitti', 'Suheli Valiyakara', 'Tinnakara', 'Parali',
            'Kalpeni Island', 'Minicoy Island', 'Andrewganj', 'Pudikkad',
            'Kunhava', 'Erambil', 'Kamili', 'Thamrachal', 'Moolikkad',
            'Pallippuram', 'Sathikulangara', 'Kovval', 'Puthur',
            'Kuthub Ali Colony', 'Metha', 'Ujra', 'Mooppanpalli',
            'Bada Jumma Masjid', 'Palli Kunnu', 'Chettilath', 'Athalpok',
            'Kendut', 'Santhi', 'Pompi', 'Malliyam', 'Achammam',
            'Puthiyathalam', 'Pattam', 'Puthupalli', 'Koottupalli',
            'Karippad', 'Beypore', 'Mampalli', 'Poyya', 'Manath',
        ],
        'Puducherry' => [
            'Puducherry', 'Karaikal', 'Yanam', 'Mahe', 'Ozhukarai',
            'Villianur', 'Bahour', 'Katterikuppam', 'Ariyankuppam',
            'Thavalakuppam', 'Muthialpet', 'Kuruchikuppam', 'Solai Nagar',
            'Seliamedu', 'Nellithope', 'Gorimedu', 'Pulianthope',
            'Kombakkadu', 'Mangalam', 'Karasur', 'Kalar', 'Sedarapet',
            'Madagadipet', 'Pattanur', 'Kariamanickam', 'Kanniakoil',
            'Thiruvandarkoil', 'Pillaiyarkuppam', 'Pudukuppam',
            'Thondamanatham', 'Korkadu', 'Kuruvinatham', 'Ram Thirtham',
            'Katteri', 'Vanur', 'Varambaiyam', 'Vikravandi', 'Embalam',
            'Selliyambalam', 'Thethampakkam', 'Kannadipet', 'Muthukadu',
            'Kallur', 'Karakambadi', 'Nallavadu', 'Pannithittu',
            'Veerampattinam', 'Sanyasikuppam', 'Kottaimedu', 'Ariyur',
            'Kaliapet', 'Pakkam', 'Alankuppam', 'Parikal', 'Periyakalapet',
            'Puducherry North', 'Puducherry South', 'Karaikal North',
            'Karaikal South', 'Neravy', 'T R Pattinam', 'Kottucherry',
            'Nedungadu', 'Tirunallar', 'Pattakudy', 'Chettiyargadda',
            'Pakkur', 'Puduthakur', 'Madalapet', 'Kovilpathu',
            'Mahindrapet', 'Thalatheru', 'Keezhavur', 'Melavur',
            'Pudupettai', 'Sembiyapattu', 'Yanam', 'Neelipalli',
            'Guzzu', 'Yanam Adi', 'Daripalli', 'Boddeti Nagaram',
            'Farampeta', 'Kotha Palem', 'Pudimadaka', 'Isakapalli',
            'Kapulapalem', 'Tikkavaram', 'Mettakur', 'Nallappareddy Palem',
            'Mahe', 'Chalakkara', 'Palloor', 'Pandakkal', 'Puthiyara',
            'Kunnumkai', 'Azhikode', 'Eramala', 'Edayattu', 'Meenchanthara',
            'Arakkal', 'Cheruthazham', 'Kattikulam', 'Pinarayi',
            'Thalassery North', 'Thalassery South', 'Kadoli', 'Moidu Park',
        ],
    ],
];
